import type {
  FunnelStage,
  PipelineDeal,
  TouchPoint,
} from "../components/crm"

export const MUFFLERMEN_DEALS: ReadonlyArray<PipelineDeal> = [
  {
    id: "deal-001",
    dealName: "Hilux SR5 — turbo-back system",
    customerName: "Mick Davis",
    vehicle: "2022 Toyota Hilux SR5",
    value: "$2,400",
    numericValue: 2400,
    expectedClose: "12 Jun",
    expectedCloseIso: "2026-06-12",
    probability: 10,
    stage: "new",
    ownerInitials: "JP",
  },
  {
    id: "deal-002",
    dealName: "Ranger Wildtrak — DPF delete",
    customerName: "Sarah Pope",
    vehicle: "2024 Ford Ranger Wildtrak",
    value: "$1,850",
    numericValue: 1850,
    expectedClose: "16 Jun",
    expectedCloseIso: "2026-06-16",
    probability: 25,
    stage: "qualified",
    ownerInitials: "JP",
  },
  {
    id: "deal-003",
    dealName: "Patrol Y62 — full custom 3in",
    customerName: "Trent Williams",
    vehicle: "2019 Nissan Patrol Y62",
    value: "$3,650",
    numericValue: 3650,
    expectedClose: "08 Jun",
    expectedCloseIso: "2026-06-08",
    probability: 50,
    stage: "quoted",
    ownerInitials: "MW",
  },
  {
    id: "deal-004",
    dealName: "Fleet — 6× Hiace muffler swap",
    customerName: "Albion Park Couriers",
    vehicle: "Fleet of 6 Toyota Hiace",
    value: "$5,280",
    numericValue: 5280,
    expectedClose: "20 Jun",
    expectedCloseIso: "2026-06-20",
    probability: 50,
    stage: "quoted",
    ownerInitials: "JP",
  },
  {
    id: "deal-005",
    dealName: "Commodore VE — cat-back",
    customerName: "Sarah Pope",
    vehicle: "2010 Holden Commodore VE SS",
    value: "$1,420",
    numericValue: 1420,
    expectedClose: "05 Jun",
    expectedCloseIso: "2026-06-05",
    probability: 80,
    stage: "verbal",
    ownerInitials: "MW",
  },
  {
    id: "deal-006",
    dealName: "Triton MQ — exhaust headers",
    customerName: "Mick Davis",
    vehicle: "2018 Mitsubishi Triton MQ",
    value: "$2,180",
    numericValue: 2180,
    expectedClose: "03 Jun",
    expectedCloseIso: "2026-06-03",
    probability: 100,
    stage: "won",
    ownerInitials: "JP",
  },
  {
    id: "deal-007",
    dealName: "Prado 150 — under-body service",
    customerName: "Trent Williams",
    vehicle: "2021 Toyota Prado 150",
    value: "$890",
    numericValue: 890,
    expectedClose: "01 Jun",
    expectedCloseIso: "2026-06-01",
    probability: 100,
    stage: "won",
    ownerInitials: "MW",
  },
]

export const MICK_TOUCH_POINTS: ReadonlyArray<TouchPoint> = [
  {
    id: "tp-1",
    kind: "payment",
    title: "Invoice INV-1043 paid — $2,180",
    body:
      "Payment cleared via direct debit at 09:14 today. No follow-up needed; remind on next service interval.",
    timestamp: "Today 09:14",
    timestampIso: "2026-05-28T09:14:00+10:00",
    actor: "Mufflermen Billing",
  },
  {
    id: "tp-2",
    kind: "in-person",
    title: "Picked up Triton from Bay 03",
    body:
      "Walked through cat-back install. Mick noted resonance at 2400 rpm, asked about resonator delete on Hilux.",
    timestamp: "Yesterday 16:40",
    timestampIso: "2026-05-27T16:40:00+10:00",
    actor: "Jordan Pham",
  },
  {
    id: "tp-3",
    kind: "sms",
    title: "Sent dyno-result PDF",
    timestamp: "Yesterday 13:02",
    timestampIso: "2026-05-27T13:02:00+10:00",
    actor: "Workshop bot",
  },
  {
    id: "tp-4",
    kind: "call",
    title: "Inbound call — quote follow-up",
    body:
      "Mick wants the Hilux SR5 turbo-back done before the Mudgee trip on the 17th. Said his mate from Albion Park might bring a Patrol in.",
    timestamp: "23 May",
    timestampIso: "2026-05-23T10:18:00+10:00",
    actor: "Jordan Pham",
  },
  {
    id: "tp-5",
    kind: "quote-sent",
    title: "Quote Q-2207 — Hilux SR5 turbo-back",
    timestamp: "22 May",
    timestampIso: "2026-05-22T09:00:00+10:00",
    actor: "Marcus Wells",
  },
  {
    id: "tp-6",
    kind: "email",
    title: "Sent fitment images + variant options",
    body:
      "Attached three system variants — mild steel, aluminised, full stainless. Recommended mid-tier aluminised for cost/ride balance.",
    timestamp: "21 May",
    timestampIso: "2026-05-21T15:20:00+10:00",
    actor: "Marcus Wells",
  },
  {
    id: "tp-7",
    kind: "dm",
    title: "Instagram DM — first contact",
    timestamp: "18 May",
    timestampIso: "2026-05-18T20:30:00+10:00",
    actor: "Mick Davis",
  },
]

export const QUOTE_TO_CASH_STAGES: ReadonlyArray<FunnelStage> = [
  { key: "lead", label: "Lead", count: 184, value: 412_300 },
  { key: "qualified", label: "Qualified", count: 112, value: 268_400 },
  { key: "quoted", label: "Quoted", count: 68, value: 184_200 },
  { key: "approved", label: "Approved", count: 42, value: 128_400 },
  { key: "invoiced", label: "Invoiced", count: 38, value: 114_800 },
  { key: "paid", label: "Paid", count: 34, value: 104_900 },
]
