/**
 * Shared CMS mock data — anchors every demo to the Oak Flats Mufflermen
 * content model: parts catalogue, suburb landings, services pages, blog,
 * vehicle library, and the workshop CRM.
 */

import type {
  BlockDefinition,
  CanvasBlock,
  CollectionRowItem,
  FieldDefinition,
  LocaleEntry,
  MediaItem,
  PageNode,
  RevisionEntry,
  SeoCheck,
  SlotGroup,
  TemplateDefinition,
} from "../components/cms"

export const CMS_BLOCKS: ReadonlyArray<BlockDefinition> = [
  {
    id: "blk-hero-shop",
    name: "Workshop hero",
    category: "hero",
    description: "Full-bleed photo of bay 3 plus headline, CTA and rating snapshot.",
    glyph: "▤",
    tone: "red",
    branded: true,
  },
  {
    id: "blk-hero-suburb",
    name: "Suburb landing hero",
    category: "hero",
    description: "Localised headline, suburb badge and click-to-call button row.",
    glyph: "◉",
    tone: "amber",
    branded: true,
  },
  {
    id: "blk-feature-grid",
    name: "Service feature grid",
    category: "feature",
    description: "Six-up icon grid mapping to exhaust, brakes, tune, dyno, log book, EV.",
    glyph: "◳",
    tone: "amber",
  },
  {
    id: "blk-feature-pricing",
    name: "Pricing tier grid",
    category: "feature",
    description: "Three-tier pricing card built on the workshop quote engine.",
    glyph: "$",
    tone: "green",
  },
  {
    id: "blk-text-prose",
    name: "Long-form prose",
    category: "text",
    description: "Editor-only rich text with anchored TOC for blog posts.",
    glyph: "¶",
    tone: "neutral",
  },
  {
    id: "blk-text-callout",
    name: "Editorial callout",
    category: "text",
    description: "Pull-quote with author attribution and rating glyph.",
    glyph: "“",
    tone: "violet",
  },
  {
    id: "blk-media-gallery",
    name: "Photo gallery",
    category: "media",
    description: "Bento-style media tray pulling from the asset library.",
    glyph: "▣",
    tone: "teal",
  },
  {
    id: "blk-media-video",
    name: "Dyno reel video",
    category: "media",
    description: "Embedded autoplay reel with reduced-motion fallback poster.",
    glyph: "▶",
    tone: "teal",
  },
  {
    id: "blk-cta-quote",
    name: "Book a quote CTA",
    category: "cta",
    description: "Conversion bar with phone + form options, suburb-aware copy.",
    glyph: "✚",
    tone: "green",
    branded: true,
  },
  {
    id: "blk-cta-newsletter",
    name: "Newsletter signup",
    category: "cta",
    description: "Email capture with brand-locked privacy copy.",
    glyph: "✉",
    tone: "green",
  },
  {
    id: "blk-form-intake",
    name: "Vehicle intake form",
    category: "form",
    description: "Multi-step intake bound to the workshop CRM submission API.",
    glyph: "✎",
    tone: "violet",
  },
  {
    id: "blk-form-feedback",
    name: "Post-service feedback",
    category: "form",
    description: "Five-question NPS survey with sentiment routing.",
    glyph: "☆",
    tone: "violet",
  },
  {
    id: "blk-embed-map",
    name: "Workshop map",
    category: "embed",
    description: "Static map + directions panel for the Oak Flats showroom.",
    glyph: "⌖",
    tone: "teal",
  },
  {
    id: "blk-embed-calendar",
    name: "Service calendar",
    category: "embed",
    description: "Bookable mechanic calendar embed with availability heatmap.",
    glyph: "▦",
    tone: "amber",
  },
]

export const CMS_CANVAS_BLOCKS: ReadonlyArray<CanvasBlock> = [
  {
    id: "canvas-hero",
    definitionId: "blk-hero-suburb",
    name: "Wollongong workshop — suburb hero",
    category: "hero",
    tone: "red",
    summary: "Hero with localised headline, drive-time pill, ratings strip.",
    glyph: "▤",
  },
  {
    id: "canvas-trust",
    definitionId: "blk-feature-grid",
    name: "Trust strip — six-up service grid",
    category: "feature",
    tone: "amber",
    summary: "Exhaust, brakes, tune, dyno, log book, EV badges.",
    glyph: "◳",
    selected: true,
  },
  {
    id: "canvas-prose",
    definitionId: "blk-text-prose",
    name: "About the workshop — long-form",
    category: "text",
    tone: "neutral",
    summary: "Founder story, certifications, 47-suburb service footprint.",
    glyph: "¶",
  },
  {
    id: "canvas-gallery",
    definitionId: "blk-media-gallery",
    name: "Bay 3 lift photo gallery",
    category: "media",
    tone: "teal",
    summary: "12 photo bento mosaic — fed from DAM smart collection.",
    glyph: "▣",
  },
  {
    id: "canvas-cta",
    definitionId: "blk-cta-quote",
    name: "Book a free quote — sticky CTA",
    category: "cta",
    tone: "green",
    summary: "Click-to-call, suburb-aware copy, opening hours.",
    glyph: "✚",
  },
]

export const CMS_SLOT_GROUPS: ReadonlyArray<SlotGroup> = [
  {
    id: "group-content",
    label: "Content",
    fields: [
      {
        id: "field-heading",
        label: "Heading",
        kind: "text",
        value: "Service feature grid",
        required: true,
        hint: "Anchor heading for screen readers — keep under 60 characters.",
      },
      {
        id: "field-body",
        label: "Supporting copy",
        kind: "textarea",
        value:
          "Six core workshop services pulled from the live pricing engine. Updates publish to /services nightly.",
        hint: "Markdown supported. Stripped before publish.",
      },
      {
        id: "field-cta-label",
        label: "Primary CTA",
        kind: "text",
        value: "Book a free assessment",
      },
    ],
  },
  {
    id: "group-layout",
    label: "Layout",
    fields: [
      {
        id: "field-columns",
        label: "Columns",
        kind: "number",
        value: 3,
        hint: "Auto-stacks to 1 column below 720px.",
      },
      {
        id: "field-alignment",
        label: "Alignment",
        kind: "select",
        value: "left",
        options: [
          { value: "left", label: "Left" },
          { value: "center", label: "Center" },
          { value: "right", label: "Right" },
        ],
      },
      {
        id: "field-accent-color",
        label: "Accent colour",
        kind: "color",
        value: "var(--primitive-red)",
      },
      {
        id: "field-hero-image",
        label: "Background image",
        kind: "image",
        value: "workshop-bay-3.jpg",
        hint: "Recommended 2400 × 1350 — JPEG quality 82.",
      },
    ],
  },
  {
    id: "group-visibility",
    label: "Visibility",
    fields: [
      {
        id: "field-publish",
        label: "Publish to live site",
        kind: "toggle",
        value: true,
      },
      {
        id: "field-show-mobile",
        label: "Show on mobile",
        kind: "toggle",
        value: true,
      },
    ],
  },
]

export const CMS_PAGE_TREE: ReadonlyArray<PageNode> = [
  {
    id: "page-home",
    slug: "",
    title: "Workshop home",
    state: "published",
    ownerInitials: "DF",
    children: [
      {
        id: "page-about",
        slug: "about",
        title: "About the workshop",
        state: "published",
        ownerInitials: "MP",
      },
      {
        id: "page-team",
        slug: "team",
        title: "Meet the crew",
        state: "draft",
        ownerInitials: "MP",
      },
    ],
  },
  {
    id: "page-services",
    slug: "services",
    title: "Services",
    state: "published",
    ownerInitials: "DF",
    children: [
      {
        id: "page-exhaust",
        slug: "services/exhaust",
        title: "Custom exhaust",
        state: "published",
        ownerInitials: "BS",
      },
      {
        id: "page-tune",
        slug: "services/tune",
        title: "Dyno tune",
        state: "scheduled",
        ownerInitials: "DF",
      },
      {
        id: "page-log-book",
        slug: "services/log-book",
        title: "Log-book service",
        state: "review",
        ownerInitials: "MP",
      },
    ],
  },
  {
    id: "page-suburbs",
    slug: "suburbs",
    title: "Suburb landings",
    state: "published",
    ownerInitials: "MP",
    children: [
      {
        id: "page-wollongong",
        slug: "suburbs/wollongong",
        title: "Wollongong",
        state: "published",
        ownerInitials: "MP",
      },
      {
        id: "page-shellharbour",
        slug: "suburbs/shellharbour",
        title: "Shellharbour",
        state: "published",
        ownerInitials: "MP",
      },
      {
        id: "page-kiama",
        slug: "suburbs/kiama",
        title: "Kiama",
        state: "draft",
        ownerInitials: "MP",
      },
      {
        id: "page-albion-park",
        slug: "suburbs/albion-park",
        title: "Albion Park",
        state: "review",
        ownerInitials: "MP",
      },
    ],
  },
  {
    id: "page-parts",
    slug: "parts",
    title: "Parts catalogue",
    state: "published",
    ownerInitials: "BS",
    children: [
      {
        id: "page-parts-mufflers",
        slug: "parts/mufflers",
        title: "Mufflers",
        state: "published",
        ownerInitials: "BS",
      },
      {
        id: "page-parts-extractors",
        slug: "parts/extractors",
        title: "Extractors & headers",
        state: "published",
        ownerInitials: "BS",
      },
    ],
  },
  {
    id: "page-blog",
    slug: "blog",
    title: "Workshop journal",
    state: "draft",
    ownerInitials: "MP",
  },
]

export const CMS_TEMPLATES: ReadonlyArray<TemplateDefinition> = [
  {
    id: "tpl-suburb-illawarra",
    title: "Suburb Landing — Illawarra",
    description: "Locale hero, drive-time pill, ratings strip, suburb-aware CTAs.",
    category: "suburb",
    blocks: 8,
    glyph: "◉",
    tone: "amber",
  },
  {
    id: "tpl-parts-exhaust",
    title: "Parts Detail — Exhaust",
    description: "Fitment chart, install footage, supplier cards, sticky add-to-quote.",
    category: "parts",
    blocks: 9,
    glyph: "▥",
    tone: "red",
  },
  {
    id: "tpl-service-booking",
    title: "Service Booking",
    description: "Three-step intake, mechanic calendar, post-service reminder card.",
    category: "service",
    blocks: 7,
    glyph: "✚",
    tone: "teal",
  },
  {
    id: "tpl-workshop-pricing",
    title: "Workshop Pricing",
    description: "Editable pricing tiers wired to the live quote engine.",
    category: "service",
    blocks: 6,
    glyph: "$",
    tone: "green",
  },
  {
    id: "tpl-landing-launch",
    title: "Campaign landing",
    description: "Big Anton headline, kinetic ribbon, sticky CTA, brand bars.",
    category: "landing",
    blocks: 5,
    glyph: "▤",
    tone: "red",
  },
  {
    id: "tpl-blog-story",
    title: "Workshop journal post",
    description: "Long-form story layout with floating quotes and inline gallery.",
    category: "blog",
    blocks: 6,
    glyph: "¶",
    tone: "violet",
  },
]

export const CMS_REVISIONS: ReadonlyArray<RevisionEntry> = [
  {
    id: "rev-2026-05-29-1",
    author: { name: "Daniel Fleuren", initials: "DF", role: "Admin" },
    action: "published",
    timestamp: "29 May · 06:01 AEST",
    summary: "Promoted Wollongong suburb landing to production — replaces old hero.",
    isLive: true,
  },
  {
    id: "rev-2026-05-29-2",
    author: { name: "Mia Patel", initials: "MP", role: "Content lead" },
    action: "edited",
    timestamp: "29 May · 05:48 AEST",
    summary: "Updated suburb copy — replaced 'best mechanic' with 'log-book specialist'.",
  },
  {
    id: "rev-2026-05-28-1",
    author: { name: "Ben Stamatakis", initials: "BS", role: "Parts catalogue" },
    action: "edited",
    timestamp: "28 May · 16:32 AEST",
    summary: "Added 4 fitment chips to the trust strip — VE Commodore, Hilux, BT-50, Triton.",
  },
  {
    id: "rev-2026-05-27-1",
    author: { name: "Daniel Fleuren", initials: "DF", role: "Admin" },
    action: "restored",
    timestamp: "27 May · 09:15 AEST",
    summary: "Rolled back hero gallery — replicate output had broken aspect ratios.",
  },
  {
    id: "rev-2026-05-26-1",
    author: { name: "Mia Patel", initials: "MP", role: "Content lead" },
    action: "scheduled",
    timestamp: "26 May · 14:20 AEST",
    summary: "Queued Albion Park suburb landing for 30 May · 08:00 AEST go-live.",
  },
  {
    id: "rev-2026-05-25-1",
    author: { name: "Mia Patel", initials: "MP", role: "Content lead" },
    action: "created",
    timestamp: "25 May · 11:04 AEST",
    summary: "Drafted Kiama suburb landing from the Illawarra template — 8 blocks.",
  },
]

export const CMS_SEO_CHECKS: ReadonlyArray<SeoCheck> = [
  {
    id: "seo-title",
    label: "Title tag length",
    status: "pass",
    detail: "58 characters — within the 30-65 character recommended band.",
  },
  {
    id: "seo-meta",
    label: "Meta description",
    status: "pass",
    detail: "152 characters — includes Wollongong, exhaust and quote intent.",
  },
  {
    id: "seo-og",
    label: "Open Graph image",
    status: "warn",
    detail: "Image is 1200×675 — recommended ratio met, but file weighs 412 KB.",
  },
  {
    id: "seo-schema",
    label: "schema.org / AutomotiveBusiness",
    status: "fail",
    detail: "Structured data block missing — Google rich results test failed.",
  },
  {
    id: "seo-h1",
    label: "Single H1",
    status: "pass",
    detail: "One H1 detected — 'Custom exhaust workshop in Wollongong'.",
  },
  {
    id: "seo-alt",
    label: "Image alt coverage",
    status: "warn",
    detail: "2 of 14 images missing alt text in the gallery block.",
  },
  {
    id: "seo-canonical",
    label: "Canonical URL",
    status: "pass",
    detail: "Canonical points to https://mufflermen.com.au/suburbs/wollongong",
  },
  {
    id: "seo-robots",
    label: "Robots policy",
    status: "pass",
    detail: "Indexable, follow — sitemap entry present.",
  },
  {
    id: "seo-internal",
    label: "Internal link count",
    status: "warn",
    detail: "4 internal links — add Albion Park and Shellharbour suburb cross-links.",
  },
  {
    id: "seo-faq-schema",
    label: "FAQ schema",
    status: "skip",
    detail: "Not required for suburb landing template.",
  },
  {
    id: "seo-localbiz",
    label: "schema.org / LocalBusiness",
    status: "fail",
    detail: "Missing — required for Mufflermen suburb landings.",
  },
  {
    id: "seo-mobile",
    label: "Mobile friendly",
    status: "pass",
    detail: "Lighthouse mobile audit — 96 / 100.",
  },
]

export const CMS_COLLECTIONS: ReadonlyArray<CollectionRowItem> = [
  {
    id: "col-parts",
    kind: "parts",
    name: "Parts catalogue",
    description: "4,200 SKUs across muffler, extractor, cat-back and tune-up lines.",
    itemCount: 4200,
    lastEditedBy: "Ben S.",
    lastEditedAt: "29 May · 04:42 AEST",
    draftCount: 12,
  },
  {
    id: "col-suburbs",
    kind: "suburbs",
    name: "Suburb landings",
    description: "47 Illawarra suburbs from Wollongong to Berry — each with localised CTAs.",
    itemCount: 47,
    lastEditedBy: "Mia P.",
    lastEditedAt: "29 May · 05:48 AEST",
    draftCount: 3,
  },
  {
    id: "col-services",
    kind: "services",
    name: "Service pages",
    description: "24 services — exhaust, brakes, dyno, EV, log book, fleet.",
    itemCount: 24,
    lastEditedBy: "Daniel F.",
    lastEditedAt: "28 May · 16:10 AEST",
  },
  {
    id: "col-blog",
    kind: "blog",
    name: "Workshop journal",
    description: "38 posts — install diaries, customer stories, build threads.",
    itemCount: 38,
    lastEditedBy: "Mia P.",
    lastEditedAt: "28 May · 12:40 AEST",
    draftCount: 4,
  },
  {
    id: "col-vehicles",
    kind: "vehicles",
    name: "Vehicle library",
    description: "180 fitment-mapped vehicles — Hilux, Triton, BT-50, VE Commodore +",
    itemCount: 180,
    lastEditedBy: "Ben S.",
    lastEditedAt: "27 May · 09:02 AEST",
  },
  {
    id: "col-team",
    kind: "team",
    name: "Workshop team",
    description: "7 staff profiles — mechanics, parts manager, owners.",
    itemCount: 7,
    lastEditedBy: "Daniel F.",
    lastEditedAt: "26 May · 18:14 AEST",
  },
]

export const CMS_PARTS_FIELDS: ReadonlyArray<FieldDefinition> = [
  {
    id: "field-part-sku",
    label: "SKU",
    kind: "text",
    required: true,
    hint: "Mufflermen part code, e.g. MUF-VE-CRP-001.",
  },
  {
    id: "field-part-name",
    label: "Part name",
    kind: "text",
    required: true,
    localized: true,
  },
  {
    id: "field-part-description",
    label: "Description",
    kind: "rich-text",
    required: false,
    localized: true,
    hint: "Two paragraphs max — appears below the spec sheet.",
  },
  {
    id: "field-part-price",
    label: "Price",
    kind: "money",
    required: true,
    hint: "AUD ex-GST — quote engine adds GST on render.",
  },
  {
    id: "field-part-fitment",
    label: "Fitment reference",
    kind: "reference",
    required: true,
    hint: "Linked to one or more entries in the vehicles collection.",
  },
  {
    id: "field-part-images",
    label: "Hero images",
    kind: "image",
    required: true,
    hint: "Minimum 3 — installed, isolated, packaging.",
  },
  {
    id: "field-part-published",
    label: "Show on catalogue",
    kind: "boolean",
    required: false,
  },
  {
    id: "field-part-launch",
    label: "Launch date",
    kind: "date",
    required: false,
  },
]

export const CMS_MEDIA_ITEMS: ReadonlyArray<MediaItem> = [
  {
    id: "media-hero-1",
    name: "Bay 3 hoist — Wollongong",
    width: 2400,
    height: 1350,
    format: "JPG",
    tone: "red",
    kicker: "HERO",
  },
  {
    id: "media-dyno",
    name: "Dyno tune session reel",
    width: 1920,
    height: 1080,
    format: "MP4",
    tone: "amber",
    kicker: "VIDEO",
  },
  {
    id: "media-cutaway",
    name: "Muffler cutaway diagram",
    width: 1600,
    height: 1200,
    format: "PNG",
    tone: "teal",
    kicker: "TECH",
  },
  {
    id: "media-team",
    name: "Workshop crew portrait",
    width: 2048,
    height: 1365,
    format: "JPG",
    tone: "violet",
    kicker: "TEAM",
  },
  {
    id: "media-extractor",
    name: "Pacemaker extractors install",
    width: 2200,
    height: 1466,
    format: "JPG",
    tone: "red",
    kicker: "INSTALL",
  },
  {
    id: "media-suburb-map",
    name: "Illawarra service map",
    width: 1600,
    height: 1000,
    format: "SVG",
    tone: "amber",
    kicker: "MAP",
  },
  {
    id: "media-ute-side",
    name: "Hilux side profile reference",
    width: 2200,
    height: 1100,
    format: "JPG",
    tone: "green",
    kicker: "REF",
  },
  {
    id: "media-spark",
    name: "Spark plug detail macro",
    width: 1500,
    height: 1500,
    format: "JPG",
    tone: "teal",
    kicker: "DETAIL",
  },
]

export const CMS_LOCALES: ReadonlyArray<LocaleEntry> = [
  {
    code: "en-AU",
    label: "English — Australia",
    completion: 100,
    pending: 0,
    reviewedAt: "29 May 2026",
  },
  {
    code: "en-NZ",
    label: "English — New Zealand",
    completion: 86,
    pending: 6,
    reviewedAt: "26 May 2026",
  },
  {
    code: "en-US",
    label: "English — United States",
    completion: 73,
    pending: 12,
    reviewedAt: "23 May 2026",
  },
  {
    code: "vi-VN",
    label: "Tiếng Việt",
    completion: 48,
    pending: 24,
    reviewedAt: "18 May 2026",
  },
  {
    code: "zh-CN",
    label: "简体中文",
    completion: 22,
    pending: 38,
    reviewedAt: "10 May 2026",
  },
]
