import {
  BadgeCheck,
  Bell,
  Box,
  Cable,
  CalendarDays,
  Cpu,
  Database,
  FileCheck,
  FileText,
  Film,
  FlaskConical,
  Folder,
  Grid3X3,
  Headphones,
  HelpCircle,
  Highlighter,
  IdCard,
  ImageIcon,
  Inbox,
  Layers3,
  Layout,
  LayoutDashboard,
  ListChecks,
  Map,
  Megaphone,
  Menu,
  MessageSquare,
  Move3d,
  Palette,
  Printer,
  Radar,
  Radio,
  Rocket,
  Search,
  Settings,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Sparkle,
  Type,
  Users,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react"

export type PrimitiveGroup =
  | "source"
  | "shared"
  | "website"
  | "parts"
  | "workshop"
  | "hermes"
  | "pulse"
  | "cms"
  | "agent"
  | "presentation"
  | "lab"

export type PrimitiveSection = {
  id: string
  href: string
  label: string
  description: string
  icon: LucideIcon
  group: PrimitiveGroup
}

export const groupOrder = [
  "source",
  "shared",
  "website",
  "parts",
  "workshop",
  "hermes",
  "pulse",
  "cms",
  "agent",
  "presentation",
  "lab",
] as const satisfies ReadonlyArray<PrimitiveGroup>

export const sections: PrimitiveSection[] = [
  // ── Overview ────────────────────────────────────────────────────────────────
  {
    id: "overview",
    href: "/ui-primitives",
    label: "Overview",
    description: "Telemetry dashboard, audit grid, and at-a-glance health.",
    icon: ListChecks,
    group: "source",
  },
  {
    id: "telemetry",
    href: "/ui-primitives/telemetry",
    label: "Telemetry",
    description: "Gauges, signal bars, and OBD-style status tiles.",
    icon: Radar,
    group: "source",
  },
  {
    id: "audit",
    href: "/ui-primitives/audit",
    label: "Audit",
    description: "Coverage of every primitive on the live website.",
    icon: FlaskConical,
    group: "source",
  },
  {
    id: "implementation",
    href: "/ui-primitives/implementation",
    label: "Agent guide",
    description: "Code blocks, setup instructions, tokens, and copy rules for AI agents.",
    icon: FileText,
    group: "source",
  },
  {
    id: "qa",
    href: "/ui-primitives/qa",
    label: "QA matrix",
    description: "Viewport, theme, accessibility, Lighthouse, asset and app-specific checks.",
    icon: BadgeCheck,
    group: "source",
  },

  // ── Foundations ─────────────────────────────────────────────────────────────
  {
    id: "foundations",
    href: "/ui-primitives/foundations",
    label: "Foundations",
    description: "Tokens, type, material, spacing, and motion.",
    icon: Layers3,
    group: "shared",
  },
  {
    id: "wireframes",
    href: "/ui-primitives/wireframes",
    label: "Wireframes",
    description: "Page, section, card, control, table, overlay, and mobile anatomy.",
    icon: Layout,
    group: "shared",
  },
  {
    id: "layouts",
    href: "/ui-primitives/layouts",
    label: "Layouts",
    description: "Gutters, max widths, split ratios, rails, bands, and responsive collapse.",
    icon: Grid3X3,
    group: "shared",
  },
  {
    id: "sizing",
    href: "/ui-primitives/sizing",
    label: "Sizing",
    description: "Buttons, icon buttons, pills, cards, rows, fields, wells, and media sizes.",
    icon: SlidersHorizontal,
    group: "shared",
  },
  {
    id: "section-patterns",
    href: "/ui-primitives/section-patterns",
    label: "Section patterns",
    description: "Full-section taxonomy for heroes, proof, dashboards, products, forms, media, and states.",
    icon: Layers3,
    group: "shared",
  },
  {
    id: "surfaces",
    href: "/ui-primitives/surfaces",
    label: "Surfaces",
    description: "Glassmorphism, neumorphism, Material 3 elevation.",
    icon: ImageIcon,
    group: "shared",
  },
  {
    id: "typography",
    href: "/ui-primitives/typography",
    label: "Typography",
    description: "10 fonts with per-family kinetic showcase.",
    icon: Type,
    group: "shared",
  },
  {
    id: "icons",
    href: "/ui-primitives/icons",
    label: "Icons",
    description: "Premium Carbon & Red raster-wrapped SVG icons plus source-backed supplier logos.",
    icon: Sparkles,
    group: "shared",
  },
  {
    id: "theming",
    href: "/ui-primitives/theming",
    label: "Theming",
    description: "Umbrella token playground — cascade changes across primitives.",
    icon: Palette,
    group: "shared",
  },

  // ── Core primitives ─────────────────────────────────────────────────────────
  {
    id: "actions",
    href: "/ui-primitives/actions",
    label: "Actions",
    description: "Buttons, icon tools, segmented controls, and CTAs.",
    icon: BadgeCheck,
    group: "shared",
  },
  {
    id: "forms",
    href: "/ui-primitives/forms",
    label: "Forms",
    description: "Inputs, field groups, validation, and selects.",
    icon: SlidersHorizontal,
    group: "shared",
  },
  {
    id: "selection",
    href: "/ui-primitives/selection",
    label: "Selection",
    description: "Tabs, chips, badges, toggles, radios, and check states.",
    icon: Grid3X3,
    group: "shared",
  },
  {
    id: "navigation",
    href: "/ui-primitives/navigation",
    label: "Navigation",
    description: "Shell, menu, command bar, breadcrumbs, and context rails.",
    icon: Menu,
    group: "shared",
  },
  {
    id: "feedback",
    href: "/ui-primitives/feedback",
    label: "Feedback",
    description: "Dialog, sheet, alert, snackbar, progress, and skeletons.",
    icon: Bell,
    group: "shared",
  },
  {
    id: "overlays",
    href: "/ui-primitives/overlays",
    label: "Overlays",
    description: "Dialogs, sheets, lightboxes, wizards, command palettes, toasts.",
    icon: Layout,
    group: "shared",
  },

  // ── Data + viz ──────────────────────────────────────────────────────────────
  {
    id: "data-display",
    href: "/ui-primitives/data-display",
    label: "Data display",
    description: "Tables, KPI cards, activity feeds, kanban, pricing.",
    icon: Database,
    group: "shared",
  },
  {
    id: "search",
    href: "/ui-primitives/search",
    label: "Search",
    description: "Global + inline search, faceted filters, results, analytics.",
    icon: Search,
    group: "shared",
  },
  {
    id: "file-browser",
    href: "/ui-primitives/file-browser",
    label: "File browser",
    description: "Tree, grid/list views, preview pane, upload, media lightbox.",
    icon: Folder,
    group: "shared",
  },

  // ── Motion + media ──────────────────────────────────────────────────────────
  {
    id: "motion",
    href: "/ui-primitives/motion",
    label: "Motion",
    description: "Reveal, stagger, magnetic, tilt, parallax, morph, scroll.",
    icon: Move3d,
    group: "shared",
  },
  {
    id: "videos",
    href: "/ui-primitives/videos",
    label: "Videos",
    description: "Hero loops, ambient backgrounds, and player primitives.",
    icon: Film,
    group: "presentation",
  },
  {
    id: "video-heroes",
    href: "/ui-primitives/video-heroes",
    label: "Video heroes",
    description: "10 distinctive hero-video variants — cinematic to scrolly.",
    icon: Film,
    group: "presentation",
  },
  {
    id: "audio",
    href: "/ui-primitives/audio",
    label: "Audio",
    description: "Players, waveform, voice memo, exhaust sound previews.",
    icon: Headphones,
    group: "presentation",
  },
  {
    id: "three-scenes",
    href: "/ui-primitives/three-scenes",
    label: "3D scenes",
    description: "R3F + Three.js — exhaust viewer, dyno, sparks, gauges.",
    icon: Cpu,
    group: "presentation",
  },
  {
    id: "brand-assets",
    href: "/ui-primitives/brand-assets",
    label: "Brand assets",
    description: "Logo, marketing imagery, hero covers, and source-of-truth presentation plates.",
    icon: Highlighter,
    group: "presentation",
  },

  // ── Workshop management ─────────────────────────────────────────────────────
  {
    id: "workshop",
    href: "/ui-primitives/workshop",
    label: "Workshop UX",
    description: "Quoting, parts, service, fitment, and job primitives.",
    icon: Wrench,
    group: "workshop",
  },
  {
    id: "workshop-scenes",
    href: "/ui-primitives/workshop-scenes",
    label: "Workshop scenes",
    description: "Production scenes — parts catalog, job ticket, weld-bay.",
    icon: Wrench,
    group: "workshop",
  },
  {
    id: "commerce",
    href: "/ui-primitives/commerce",
    label: "Parts commerce",
    description: "Cart, checkout, order, shipping, payments, gift cards for parts flows.",
    icon: ShoppingCart,
    group: "parts",
  },
  {
    id: "crm",
    href: "/ui-primitives/crm",
    label: "CRM",
    description: "Customers, deal pipeline, touch points, lead scoring.",
    icon: Users,
    group: "workshop",
  },
  {
    id: "sales-leads",
    href: "/ui-primitives/sales-leads",
    label: "Sales leads",
    description:
      "Top-of-funnel — capture, qualification, scoring, source ROI, SLA, import wizard.",
    icon: Sparkle,
    group: "workshop",
  },
  {
    id: "kyc",
    href: "/ui-primitives/kyc",
    label: "KYC",
    description: "Verification, sanctions, tax info, beneficial owners.",
    icon: IdCard,
    group: "cms",
  },
  {
    id: "calendar",
    href: "/ui-primitives/calendar",
    label: "Calendar",
    description: "Month / week / day / agenda + pickers + availability.",
    icon: CalendarDays,
    group: "workshop",
  },

  // ── Parts system ────────────────────────────────────────────────────────────
  {
    id: "parts-catalog",
    href: "/ui-primitives/workshop-scenes/parts-catalog",
    label: "Parts catalog",
    description: "Fitment search, product cards, supplier media, and parts result states.",
    icon: Cable,
    group: "parts",
  },
  {
    id: "parts-webpage",
    href: "/ui-primitives/marketing/full-landing",
    label: "Parts webpage",
    description: "Webpage layout grammar for category, service, and parts landing pages.",
    icon: Layout,
    group: "parts",
  },

  // ── Control, CMS, and agent UI ──────────────────────────────────────────────
  {
    id: "auth",
    href: "/ui-primitives/auth",
    label: "Auth",
    description: "Login, signup, reset, 2FA, onboarding scenes.",
    icon: ShieldCheck,
    group: "cms",
  },
  {
    id: "account",
    href: "/ui-primitives/account",
    label: "Account",
    description: "Profile, billing, team, integrations, sessions, danger zone.",
    icon: Settings,
    group: "cms",
  },
  {
    id: "permissions",
    href: "/ui-primitives/permissions",
    label: "Permissions",
    description: "Roles, ACL, matrix, JIT access, audit trail, policies.",
    icon: ShieldCheck,
    group: "cms",
  },
  {
    id: "notifications",
    href: "/ui-primitives/notifications",
    label: "Notifications",
    description: "Bell, popover, channel matrix, rule builder, previews.",
    icon: Bell,
    group: "pulse",
  },
  {
    id: "onboarding",
    href: "/ui-primitives/onboarding",
    label: "Onboarding",
    description: "Welcome, setup checklist, milestones, achievements.",
    icon: Rocket,
    group: "cms",
  },
  {
    id: "inbox",
    href: "/ui-primitives/inbox",
    label: "Inbox",
    description: "Human-to-human messaging — conversations, threads, reactions.",
    icon: Inbox,
    group: "agent",
  },
  {
    id: "ai",
    href: "/ui-primitives/ai",
    label: "AI assistant",
    description: "Chat thread, prompts, tool calls, citations, conversation rail.",
    icon: MessageSquare,
    group: "agent",
  },
  {
    id: "hermes-agent",
    href: "/ui-primitives/hermes-agent",
    label: "Hermes agent",
    description: "Control plane: chat, run timeline, tools, persona, safety, handoff, transcripts.",
    icon: Workflow,
    group: "agent",
  },
  {
    id: "torque",
    href: "/ui-primitives/torque/owner-dashboard",
    label: "Torque",
    description:
      "Business assistant surfaces: owner cockpit, chat, approvals, CMS, social, operations, and agent tooling.",
    icon: Cpu,
    group: "agent",
  },
  {
    id: "torque-channels",
    href: "/ui-primitives/torque/channels",
    label: "Torque channels",
    description: "Connected Telegram, chat, SMS, email, and Discord health with routing rules.",
    icon: Radio,
    group: "agent",
  },
  {
    id: "torque-analytics",
    href: "/ui-primitives/torque/analytics",
    label: "Torque analytics",
    description: "Revenue, bookings, local SEO, social reach, top pages, and assistant cost.",
    icon: Radar,
    group: "agent",
  },
  {
    id: "torque-file-browser",
    href: "/ui-primitives/torque/file-browser",
    label: "Torque files",
    description: "Workshop asset library with folders, preview, upload, versions, and selection.",
    icon: Folder,
    group: "agent",
  },
  {
    id: "torque-logs-viewer",
    href: "/ui-primitives/torque/logs-viewer",
    label: "Torque logs",
    description: "Structured log stream with search, filters, live-tail, and expandable rows.",
    icon: FileText,
    group: "agent",
  },
  {
    id: "torque-model-manager",
    href: "/ui-primitives/torque/model-manager",
    label: "Torque models",
    description: "Model availability, default route, token usage, cost charts, and budget posture.",
    icon: Cpu,
    group: "agent",
  },
  {
    id: "torque-mobile-shell",
    href: "/ui-primitives/torque/mobile-shell",
    label: "Torque mobile",
    description: "Phone shell composition with chat, quote approval, drawer, tabs, and bottom sheet.",
    icon: Smartphone,
    group: "agent",
  },
  {
    id: "torque-notifications",
    href: "/ui-primitives/torque/notifications",
    label: "Torque notifications",
    description: "Grouped sign-off, system, activity, social, and SEO alerts with inbox actions.",
    icon: Bell,
    group: "agent",
  },
  {
    id: "torque-profile",
    href: "/ui-primitives/torque/profile",
    label: "Torque profile",
    description: "Owner identity, plan, activity, notification preferences, devices, and actions.",
    icon: Users,
    group: "agent",
  },
  {
    id: "torque-scheduled-jobs",
    href: "/ui-primitives/torque/scheduled-jobs",
    label: "Torque jobs",
    description: "Cron automations with next run, last status, run history, and toggles.",
    icon: CalendarDays,
    group: "agent",
  },
  {
    id: "torque-web-terminal",
    href: "/ui-primitives/torque/web-terminal",
    label: "Torque terminal",
    description: "Read-only operator console for sessions, scrollback, metrics, and run status.",
    icon: Cable,
    group: "agent",
  },
  {
    id: "torque-states-overview",
    href: "/ui-primitives/torque/states-overview",
    label: "Torque states",
    description: "Empty, loading, fault, offline, maintenance, and success screens for Torque.",
    icon: Zap,
    group: "agent",
  },
  {
    id: "workflows",
    href: "/ui-primitives/workflows",
    label: "Workflows",
    description: "Trigger / action / condition nodes, canvas, run history.",
    icon: Workflow,
    group: "agent",
  },
  {
    id: "forms-gallery",
    href: "/ui-primitives/forms-gallery",
    label: "Forms gallery",
    description: "10 production form patterns — contact, booking, quote, survey.",
    icon: SlidersHorizontal,
    group: "website",
  },
  {
    id: "states",
    href: "/ui-primitives/states",
    label: "System states",
    description: "404, 500, maintenance, empty, offline, success.",
    icon: Zap,
    group: "cms",
  },
  {
    id: "help-docs",
    href: "/ui-primitives/help-docs",
    label: "Help & docs",
    description: "Tour, callouts, TOC, API reference, code playground.",
    icon: HelpCircle,
    group: "cms",
  },
  {
    id: "marketing",
    href: "/ui-primitives/marketing",
    label: "Marketing",
    description: "Hero, features, testimonials, pricing, FAQ, footer, full landing.",
    icon: Megaphone,
    group: "website",
  },
  {
    id: "dashboards",
    href: "/ui-primitives/dashboards",
    label: "Persona dashboards",
    description: "Workshop manager, front desk, parts, customer, executive.",
    icon: LayoutDashboard,
    group: "hermes",
  },
  {
    id: "mobile-shell",
    href: "/ui-primitives/mobile-shell",
    label: "Mobile shell",
    description: "Top bar, bottom nav, drawer, action sheet, FAB, modal sheet.",
    icon: Smartphone,
    group: "shared",
  },
  {
    id: "emails",
    href: "/ui-primitives/emails",
    label: "Emails",
    description: "12 transactional templates — welcome to abandoned cart.",
    icon: Inbox,
    group: "website",
  },
  {
    id: "print-docs",
    href: "/ui-primitives/print-docs",
    label: "Print docs",
    description: "Invoice, receipt, work order, quote, compliance cert, barcode/QR.",
    icon: Printer,
    group: "workshop",
  },
  {
    id: "maps",
    href: "/ui-primitives/maps",
    label: "Maps",
    description: "Static map, pins, radius, workshop locator, region heatmap.",
    icon: Map,
    group: "website",
  },

  // ── Brand mirrors ───────────────────────────────────────────────────────────
  {
    id: "hermes",
    href: "/ui-primitives/hermes",
    label: "Hermes mirror",
    description: "Hermes dashboard primitives — KPIs, feed, pipeline, command.",
    icon: Box,
    group: "hermes",
  },
  {
    id: "mufflerpulse",
    href: "/ui-primitives/mufflerpulse",
    label: "Muffler Pulse",
    description: "Postiz rebrand — channels, composer, calendar, performance.",
    icon: Radio,
    group: "pulse",
  },

  // ── Lab ─────────────────────────────────────────────────────────────────────
  {
    id: "production",
    href: "/ui-primitives/production",
    label: "Production",
    description: "Coverage matrix, release gates, and handoff standards.",
    icon: FileCheck,
    group: "source",
  },
  {
    id: "sandbox",
    href: "/ui-primitives/sandbox",
    label: "Sandbox",
    description: "One-off, unique, non-reusable experiments before graduation.",
    icon: Sparkle,
    group: "lab",
  },

  // ── Newly wired: content systems, icon families, control + builder ──────────
  {
    id: "blog-system",
    href: "/ui-primitives/blog-system",
    label: "Blog system",
    description: "Editorial blog kit — index grid, post layout, TOC, author byline, share, newsletter.",
    icon: FileText,
    group: "website",
  },
  {
    id: "news-system",
    href: "/ui-primitives/news-system",
    label: "News system",
    description: "Newsroom primitives — index, cards, breaking banner, hero, press release, ticker.",
    icon: Megaphone,
    group: "website",
  },
  {
    id: "torque-mascot",
    href: "/ui-primitives/torque-mascot",
    label: "Torque mascot",
    description: "The Torque AI-mechanic avatar with animated personality states.",
    icon: Sparkle,
    group: "agent",
  },
  {
    id: "page-builder",
    href: "/ui-primitives/builder/canvas",
    label: "Page builder",
    description: "Drag-and-drop CMS canvas with undo/redo and an approval-gated publish flow.",
    icon: Layout,
    group: "cms",
  },
  {
    id: "section-library",
    href: "/ui-primitives/section-library/web",
    label: "Section library",
    description: "Production-ready page sections composed from existing primitives.",
    icon: Layers3,
    group: "cms",
  },
]

export const groupTitles: Record<PrimitiveGroup, string> = {
  source: "00 / Source of truth",
  shared: "01 / Shared DNA",
  website: "02 / Website system",
  parts: "03 / Parts system",
  workshop: "04 / Workshop management",
  hermes: "05 / Hermes dashboards",
  pulse: "06 / Muffler Pulse",
  cms: "07 / CMS primitives",
  agent: "08 / Agent UI primitives",
  presentation: "09 / Marketing assets",
  lab: "10 / Lab",
}

export const sidebarCoverageLabel = "registry-backed primitive catalogue"
