import type { PrimitiveFamilyManifest } from "../types"

const importPath = "@/app/ui-primitives/components/block-editor"

const manifest: PrimitiveFamilyManifest = {
  family: "block-editor",
  title: "Block editor",
  group: "Content",
  summary:
    "14 editorial blocks sharing the BlockData<T> envelope and render/edit/preview/error modes, wrapped in a common BlockShell.",
  entries: [
    {
      key: "block-editor/gallery",
      family: "block-editor",
      name: "GalleryBlock",
      label: "Gallery",
      description:
        "Image gallery rendering grid / carousel / masonry layouts with numbered figures, captions, and a layout-picker toolbar.",
      kind: "block",
      blockType: "gallery",
      importPath,
      routeHref: "/ui-primitives/block-editor/gallery",
      tags: ["gallery", "media", "layout", "editorial"],
      status: "captured",
    },
    {
      key: "block-editor/code",
      family: "block-editor",
      name: "CodeBlock",
      label: "Code block",
      description:
        "Syntax-highlighted code snippet with language/theme pickers, optional line numbers, filename header, and copy-to-clipboard.",
      kind: "block",
      blockType: "code",
      importPath,
      routeHref: "/ui-primitives/block-editor/code",
      tags: ["code", "syntax", "developer"],
      status: "captured",
    },
    {
      key: "block-editor/table",
      family: "block-editor",
      name: "TableBlock",
      label: "Table",
      description:
        "Data table with sortable columns, per-cell formatting (text/AUD currency/number/percent), caption, and add-row editing.",
      kind: "block",
      blockType: "table",
      importPath,
      routeHref: "/ui-primitives/block-editor/table",
      tags: ["table", "data", "sortable"],
      status: "captured",
    },
    {
      key: "block-editor/embed",
      family: "block-editor",
      name: "EmbedBlock",
      label: "Embed",
      description:
        "External media embed card for YouTube/Vimeo/CodePen/Twitter with provider badge and aspect-ratio picker.",
      kind: "block",
      blockType: "embed",
      importPath,
      routeHref: "/ui-primitives/block-editor/embed",
      tags: ["embed", "media", "oembed"],
      status: "captured",
    },
    {
      key: "block-editor/quote",
      family: "block-editor",
      name: "QuoteBlock",
      label: "Quote",
      description:
        "Pull-quote / blockquote with author, citation, and optional initials portrait; plain or with-image variants.",
      kind: "block",
      blockType: "quote",
      importPath,
      routeHref: "/ui-primitives/block-editor/quote",
      tags: ["quote", "testimonial", "editorial"],
      status: "captured",
    },
    {
      key: "block-editor/poll",
      family: "block-editor",
      name: "PollBlock",
      label: "Poll",
      description:
        "Multi-choice poll with live percentage result bars, vote totals, single/multi-select toggle and optional close date.",
      kind: "block",
      blockType: "poll",
      importPath,
      routeHref: "/ui-primitives/block-editor/poll",
      tags: ["poll", "vote", "interactive"],
      status: "captured",
    },
    {
      key: "block-editor/code-sandbox",
      family: "block-editor",
      name: "CodeSandboxBlock",
      label: "Code sandbox",
      description: "Live HTML/CSS/JS playground with switchable editor panes and a mocked preview pane.",
      kind: "block",
      blockType: "codeSandbox",
      importPath,
      routeHref: "/ui-primitives/block-editor/code-sandbox",
      tags: ["sandbox", "code", "playground"],
      status: "captured",
    },
    {
      key: "block-editor/timeline",
      family: "block-editor",
      name: "TimelineBlock",
      label: "Timeline",
      description:
        "Vertical event timeline with date/granularity, label, description, per-event tone, and add-event control.",
      kind: "block",
      blockType: "timeline",
      importPath,
      routeHref: "/ui-primitives/block-editor/timeline",
      tags: ["timeline", "history", "events"],
      status: "captured",
    },
    {
      key: "block-editor/divider",
      family: "block-editor",
      name: "DividerBlock",
      label: "Divider",
      description: "Section separator with line / dot / icon / wave / zigzag variants and an optional inline label.",
      kind: "block",
      blockType: "divider",
      importPath,
      routeHref: "/ui-primitives/block-editor/divider",
      tags: ["divider", "separator", "layout"],
      status: "captured",
    },
    {
      key: "block-editor/video",
      family: "block-editor",
      name: "VideoBlock",
      label: "Video",
      description: "Video block with poster frame, play affordance, formatted duration, chapter list, and captions toggle.",
      kind: "block",
      blockType: "video",
      importPath,
      routeHref: "/ui-primitives/block-editor/video",
      tags: ["video", "media", "chapters"],
      status: "captured",
    },
    {
      key: "block-editor/callout",
      family: "block-editor",
      name: "CalloutBlock",
      label: "Callout",
      description: "Info / warning / tip / danger callout with icon, title, body, and optional dismiss control.",
      kind: "block",
      blockType: "callout",
      importPath,
      routeHref: "/ui-primitives/block-editor/callout",
      tags: ["callout", "note", "admonition"],
      status: "captured",
    },
    {
      key: "block-editor/checklist",
      family: "block-editor",
      name: "ChecklistBlock",
      label: "Checklist",
      description: "Interactive checklist with toggleable items, a done/total counter, and a linear completion meter.",
      kind: "block",
      blockType: "checklist",
      importPath,
      routeHref: "/ui-primitives/block-editor/checklist",
      tags: ["checklist", "todo", "interactive"],
      status: "captured",
    },
    {
      key: "block-editor/accordion",
      family: "block-editor",
      name: "AccordionBlock",
      label: "Accordion",
      description: "Collapsible Q&A accordion with per-entry toggle and expand-all / collapse-all controls.",
      kind: "block",
      blockType: "accordion",
      importPath,
      routeHref: "/ui-primitives/block-editor/accordion",
      tags: ["accordion", "faq", "collapsible"],
      status: "captured",
    },
    {
      key: "block-editor/cta",
      family: "block-editor",
      name: "CtaBlock",
      label: "Call to action",
      description:
        "Call-to-action card with heading, body, accent-tone picker, optional background image, and a linked button.",
      kind: "block",
      blockType: "cta",
      importPath,
      routeHref: "/ui-primitives/block-editor/cta",
      tags: ["cta", "conversion", "marketing"],
      status: "captured",
    },
    {
      key: "block-editor/block-shell",
      family: "block-editor",
      name: "BlockShell",
      label: "Block shell",
      description:
        "Shared chrome wrapper rendering the block surface, edit-mode toolbar header, and the error/alert state for every block.",
      kind: "primitive",
      importPath,
      tags: ["shell", "wrapper", "chrome"],
      status: "captured",
    },
  ],
}

export default manifest
