import type { PrimitiveFamilyManifest } from "../types"

const importPath = "@/app/ui-primitives/components/data-display"

const manifest: PrimitiveFamilyManifest = {
  family: "data-display",
  title: "Data display",
  group: "Data",
  summary: "Dashboard data widgets: tables, metric blocks, activity feeds, kanban, counters, badge grids.",
  entries: [
    {
      key: "data-display/data-table",
      family: "data-display",
      name: "DataTable",
      label: "Data table",
      description:
        "Generic typed table with sortable column heads, row-selection checkboxes, zebra striping, density modes, caption/kicker, and an empty state.",
      kind: "widget",
      importPath,
      routeHref: "/ui-primitives/data-display/table",
      tags: ["table", "sortable", "selectable", "dashboard"],
      status: "improved",
    },
    {
      key: "data-display/dashboard-card",
      family: "data-display",
      name: "DashboardCard",
      label: "Dashboard card",
      description:
        "KPI tile with icon, big value/unit, delta chip, sparkline slot, and footer link across glass/neuo/material surfaces.",
      kind: "widget",
      importPath,
      routeHref: "/ui-primitives/data-display/dashboard-card",
      tags: ["kpi", "card", "metric", "dashboard"],
      status: "improved",
    },
    {
      key: "data-display/metric-block",
      family: "data-display",
      name: "MetricBlock",
      label: "Metric block",
      description:
        "Inline definition-list band of label/value/delta metrics joined as a single bordered row for dense dashboards.",
      kind: "widget",
      importPath,
      routeHref: "/ui-primitives/data-display/metric-block",
      tags: ["metric", "stats", "delta", "dashboard"],
      status: "improved",
    },
    {
      key: "data-display/activity-feed",
      family: "data-display",
      name: "ActivityFeed",
      label: "Activity feed",
      description:
        "Vertical timeline of tone-tinted events with actor avatar, timestamp, description, and an auto-animated live-polite aria region.",
      kind: "widget",
      importPath,
      routeHref: "/ui-primitives/data-display/activity-feed",
      tags: ["feed", "timeline", "activity", "live"],
      status: "improved",
    },
    {
      key: "data-display/notification-inbox",
      family: "data-display",
      name: "NotificationInbox",
      label: "Notification inbox",
      description:
        "Three-tab inbox panel (unread/all/mentions) with tone status icons, per-item mark-read and dismiss actions, and a mark-all-read footer.",
      kind: "widget",
      importPath,
      routeHref: "/ui-primitives/data-display/notification-inbox",
      tags: ["notifications", "inbox", "tabs", "alerts"],
      status: "improved",
    },
    {
      key: "data-display/status-badge-grid",
      family: "data-display",
      name: "StatusBadgeGrid",
      label: "Status badge grid",
      description:
        "Catalogue grid rendering every badge tone (info/success/warn/error/neutral/brand) across three sizes and three shapes.",
      kind: "widget",
      importPath,
      routeHref: "/ui-primitives/data-display/status-badge-grid",
      tags: ["badge", "status", "catalogue", "grid"],
      status: "improved",
    },
    {
      key: "data-display/status-badge",
      family: "data-display",
      name: "StatusBadge",
      label: "Status badge",
      description: "Single status pill rendering a labeled badge for a given tone, size, and shape (pill/square/dot).",
      kind: "primitive",
      importPath,
      routeHref: "/ui-primitives/data-display/status-badge-grid",
      tags: ["badge", "status", "pill", "label"],
      status: "improved",
    },
    {
      key: "data-display/live-counter-card",
      family: "data-display",
      name: "LiveCounterCard",
      label: "Live counter card",
      description:
        "Animated count-up value with a pulsing live pill, optional prefix/unit, subhead, trailing sparkline, and meta/source footer.",
      kind: "widget",
      importPath,
      routeHref: "/ui-primitives/data-display/live-counter-card",
      tags: ["counter", "live", "countup", "sparkline"],
      status: "improved",
    },
    {
      key: "data-display/comparison-table",
      family: "data-display",
      name: "ComparisonTable",
      label: "Comparison table",
      description:
        "Multi-column plan comparison with popular-column emphasis, ribbon, per-feature rows, and check/cross/dot/text indicators.",
      kind: "widget",
      importPath,
      routeHref: "/ui-primitives/data-display/comparison-table",
      tags: ["comparison", "table", "pricing", "features"],
      status: "improved",
    },
    {
      key: "data-display/pricing-tier-card",
      family: "data-display",
      name: "PricingTierCard",
      label: "Pricing tier card",
      description:
        "Single pricing tier card with kicker/tagline, currency-aware price and period, included/excluded features, optional ribbon, and CTA.",
      kind: "primitive",
      importPath,
      routeHref: "/ui-primitives/data-display/pricing-tier-card",
      tags: ["pricing", "tier", "plan", "cta"],
      status: "improved",
    },
    {
      key: "data-display/kanban-board",
      family: "data-display",
      name: "KanbanBoard",
      label: "Kanban board",
      description:
        "Multi-column board (backlog/progress/review/done) with per-card code, priority dot, tag chips, due date, and an avatar assignee stack.",
      kind: "widget",
      importPath,
      routeHref: "/ui-primitives/data-display/kanban-board",
      tags: ["kanban", "board", "tasks", "columns"],
      status: "improved",
    },
    {
      key: "data-display/media-tray",
      family: "data-display",
      name: "MediaTray",
      label: "Media tray",
      description:
        "Horizontal snap scroller of media figures with optional overlay tag, image or placeholder, and figcaption title/meta.",
      kind: "widget",
      importPath,
      routeHref: "/ui-primitives/data-display/media-tray",
      tags: ["media", "gallery", "scroller", "figures"],
      status: "improved",
    },
  ],
}

export default manifest
