/**
 * Family-manifest barrel — AUTO-GENERATED by
 * tools/registry/build-fragments-from-workflow.mjs. Do not edit by hand;
 * re-run the generator after a capture wave.
 */

import type { PrimitiveFamilyManifest } from "../types"

import abRuntime from "./ab-runtime"
import account from "./account"
import accounting from "./accounting"
import actions from "./actions"
import adminHub from "./admin-hub"
import adrCompliance from "./adr-compliance"
import ai from "./ai"
import aiWorkflow from "./ai-workflow"
import apiConsole from "./api-console"
import apiExplorer from "./api-explorer"
import assetCdn from "./asset-cdn"
import assetLibrary from "./asset-library"
import audio from "./audio"
import auth from "./auth"
import authDeep from "./auth-deep"
import backups from "./backups"
import bayDisplay from "./bay-display"
import billing from "./billing"
import blockEditor from "./block-editor"
import bookingWidget from "./booking-widget"
import brandControl from "./brand-control"
import branding from "./branding"
import bulkOps from "./bulk-ops"
import calendar from "./calendar"
import charts from "./charts"
import chrome from "./chrome"
import cloudCosts from "./cloud-costs"
import cms from "./cms"
import codeDiff from "./code-diff"
import collabDeep from "./collab-deep"
import comments from "./comments"
import commerce from "./commerce"
import compliance from "./compliance"
import connectors from "./connectors"
import contentStudio from "./content-studio"
import crm from "./crm"
import customerPortal from "./customer-portal"
import customerSuccess from "./customer-success"
import dashboards from "./dashboards"
import dataDisplay from "./data-display"
import dataImport from "./data-import"
import dbAdmin from "./db-admin"
import deployConsole from "./deploy-console"
import devExperience from "./dev-experience"
import docsSuite from "./docs-suite"
import emailBuilder from "./email-builder"
import emails from "./emails"
import experiments from "./experiments"
import featureFlags from "./feature-flags"
import fileBrowser from "./file-browser"
import formBuilder from "./form-builder"
import formsGallery from "./forms-gallery"
import formsPlatform from "./forms-platform"
import formsSystem from "./forms-system"
import helpDocs from "./help-docs"
import hermesAgent from "./hermes-agent"
import icons from "./icons"
import inbox from "./inbox"
import inventory from "./inventory"
import inventoryDeep from "./inventory-deep"
import jobQueue from "./job-queue"
import kyc from "./kyc"
import landingPages from "./landing-pages"
import liveBroadcast from "./live-broadcast"
import liveChat from "./live-chat"
import localization from "./localization"
import localizationDeep from "./localization-deep"
import locationsPages from "./locations-pages"
import loyalty from "./loyalty"
import maps from "./maps"
import marketing from "./marketing"
import sectionBlocks from "./section-blocks"
import marketingAutomation from "./marketing-automation"
import marketingCampaigns from "./marketing-campaigns"
import marketplace from "./marketplace"
import mlExperiments from "./ml-experiments"
import mobileShell from "./mobile-shell"
import motion from "./motion"
import notifications from "./notifications"
import notificationsSystem from "./notifications-system"
import observability from "./observability"
import onboarding from "./onboarding"
import overlays from "./overlays"
import partsPages from "./parts-pages"
import permissions from "./permissions"
import photoEditor from "./photo-editor"
import posCheckout from "./pos-checkout"
import primitives from "./primitives"
import printDocs from "./print-docs"
import productTours from "./product-tours"
import pwaShell from "./pwa-shell"
import quotes from "./quotes"
import realtimeCollab from "./realtime-collab"
import reports from "./reports"
import reportsDeep from "./reports-deep"
import reviews from "./reviews"
import roster from "./roster"
import salesLeads from "./sales-leads"
import screenRecorder from "./screen-recorder"
import search from "./search"
import servicesAreasPages from "./services-areas-pages"
import socialScheduler from "./social-scheduler"
import spreadsheet from "./spreadsheet"
import states from "./states"
import statusPage from "./status-page"
import storefront from "./storefront"
import supplierPortal from "./supplier-portal"
import support from "./support"
import surfaces from "./surfaces"
import surveys from "./surveys"
import systemOnboarding from "./system-onboarding"
import telemetry from "./telemetry"
import theming from "./theming"
import threeScenes from "./three-scenes"
import topology from "./topology"
import torque from "./torque"
import typography from "./typography"
import unifiedInbox from "./unified-inbox"
import vehicleData from "./vehicle-data"
import vehicles from "./vehicles"
import videoEditor from "./video-editor"
import videoHeroes from "./video-heroes"
import whiteboard from "./whiteboard"
import workflowEngine from "./workflow-engine"
import workflows from "./workflows"
import workshopFloorLive from "./workshop-floor-live"
import workshopOps from "./workshop-ops"
import workshopScenes from "./workshop-scenes"
// Newly wired families (content systems + Torque mascot).
import blogSystem from "./blog-system"
import newsSystem from "./news-system"
import torqueMascot from "./torque-mascot"

export const familyManifests: readonly PrimitiveFamilyManifest[] = [
  abRuntime,
  account,
  accounting,
  actions,
  adminHub,
  adrCompliance,
  ai,
  aiWorkflow,
  apiConsole,
  apiExplorer,
  assetCdn,
  assetLibrary,
  audio,
  auth,
  authDeep,
  backups,
  bayDisplay,
  billing,
  blockEditor,
  bookingWidget,
  brandControl,
  branding,
  bulkOps,
  calendar,
  charts,
  chrome,
  cloudCosts,
  cms,
  codeDiff,
  collabDeep,
  comments,
  commerce,
  compliance,
  connectors,
  contentStudio,
  crm,
  customerPortal,
  customerSuccess,
  dashboards,
  dataDisplay,
  dataImport,
  dbAdmin,
  deployConsole,
  devExperience,
  docsSuite,
  emailBuilder,
  emails,
  experiments,
  featureFlags,
  fileBrowser,
  formBuilder,
  formsGallery,
  formsPlatform,
  formsSystem,
  helpDocs,
  hermesAgent,
  icons,
  inbox,
  inventory,
  inventoryDeep,
  jobQueue,
  kyc,
  landingPages,
  liveBroadcast,
  liveChat,
  localization,
  localizationDeep,
  locationsPages,
  loyalty,
  maps,
  marketing,
  sectionBlocks,
  marketingAutomation,
  marketingCampaigns,
  marketplace,
  mlExperiments,
  mobileShell,
  motion,
  notifications,
  notificationsSystem,
  observability,
  onboarding,
  overlays,
  partsPages,
  permissions,
  photoEditor,
  posCheckout,
  primitives,
  printDocs,
  productTours,
  pwaShell,
  quotes,
  realtimeCollab,
  reports,
  reportsDeep,
  reviews,
  roster,
  salesLeads,
  screenRecorder,
  search,
  servicesAreasPages,
  socialScheduler,
  spreadsheet,
  states,
  statusPage,
  storefront,
  supplierPortal,
  support,
  surfaces,
  surveys,
  systemOnboarding,
  telemetry,
  theming,
  threeScenes,
  topology,
  torque,
  typography,
  unifiedInbox,
  vehicleData,
  vehicles,
  videoEditor,
  videoHeroes,
  whiteboard,
  workflowEngine,
  workflows,
  workshopFloorLive,
  workshopOps,
  workshopScenes,
  blogSystem,
  newsSystem,
  torqueMascot,
]
