import type { PrimitiveFamilyManifest } from "../types"

const importPath = "@/app/ui-primitives/components/marketing"

const manifest: PrimitiveFamilyManifest = {
  family: "marketing",
  title: "Marketing sections",
  group: "Marketing",
  summary: "Marketing/landing sections: heroes, feature grids, testimonials, CTAs, pricing, FAQ, logo clouds.",
  entries: [
    {
      key: "marketing/text-first-hero",
      family: "marketing",
      name: "TextFirstHero",
      label: "Text-first hero",
      description:
        "Editorial text-first hero with kicker, display headline, subhead, primary/secondary CTAs, optional trust strip, and layout variants.",
      kind: "block",
      blockType: "text-first-hero",
      importPath,
      routeHref: "/ui-primitives/marketing/text-first-hero",
      tags: ["hero", "landing", "cta"],
      status: "improved",
    },
    {
      key: "marketing/feature-grid",
      family: "marketing",
      name: "FeatureGrid",
      label: "Feature grid",
      description:
        "Reveal-animated feature grid in 2/3/4 columns; each item has icon, title, body, optional link, under an optional header.",
      kind: "block",
      blockType: "feature-grid",
      importPath,
      routeHref: "/ui-primitives/marketing/feature-grid",
      tags: ["features", "grid", "landing"],
      status: "improved",
    },
    {
      key: "marketing/feature-spotlight",
      family: "marketing",
      name: "FeatureSpotlight",
      label: "Feature spotlight",
      description:
        "Single feature row pairing a visual with copy (kicker, heading, body, bullets, action) in a reversible layout with reveal motion.",
      kind: "block",
      blockType: "feature-spotlight",
      importPath,
      routeHref: "/ui-primitives/marketing/feature-spotlight",
      tags: ["feature", "spotlight", "storytelling"],
      status: "improved",
    },
    {
      key: "marketing/testimonial-wall",
      family: "marketing",
      name: "TestimonialWall",
      label: "Testimonial wall",
      description:
        "Masonry-style testimonial grid with varied card heights, star ratings, quote, and avatar attribution.",
      kind: "block",
      blockType: "testimonial-wall",
      importPath,
      routeHref: "/ui-primitives/marketing/testimonial-wall",
      tags: ["testimonials", "social-proof", "reviews"],
      status: "improved",
    },
    {
      key: "marketing/pricing-cta-section",
      family: "marketing",
      name: "PricingCtaSection",
      label: "Pricing CTA section",
      description:
        "Pricing section wrapping a ComparisonTable with a header, optional body/footnote, and a final CTA action row.",
      kind: "block",
      blockType: "pricing-cta-section",
      importPath,
      routeHref: "/ui-primitives/marketing/pricing-cta",
      tags: ["pricing", "cta", "comparison"],
      status: "improved",
    },
    {
      key: "marketing/faq-accordion",
      family: "marketing",
      name: "FaqAccordion",
      label: "FAQ accordion",
      description:
        "Base UI accordion of question/answer items with rich answer panels, chevron indicators, and an optional default-open item.",
      kind: "block",
      blockType: "faq-accordion",
      importPath,
      routeHref: "/ui-primitives/marketing/faq-accordion",
      tags: ["faq", "accordion", "support"],
      status: "improved",
    },
    {
      key: "marketing/logo-cloud",
      family: "marketing",
      name: "LogoCloud",
      label: "Logo cloud",
      description:
        "Muted wall of partner brand-mark SVGs with accessible labels and a staggered fade-in reveal under an optional header.",
      kind: "block",
      blockType: "logo-cloud",
      importPath,
      routeHref: "/ui-primitives/marketing/logo-cloud",
      tags: ["logos", "trust", "partners"],
      status: "improved",
    },
    {
      key: "marketing/stat-counter-row",
      family: "marketing",
      name: "StatCounterRow",
      label: "Stat counter row",
      description:
        "Row of big stat counters with in-view count-up animation, per-entry tone, prefix/suffix/decimals, label, and supporting copy.",
      kind: "block",
      blockType: "stat-counter-row",
      importPath,
      routeHref: "/ui-primitives/marketing/stat-counter-row",
      tags: ["stats", "metrics", "count-up"],
      status: "improved",
    },
    {
      key: "marketing/newsletter-cta",
      family: "marketing",
      name: "NewsletterCta",
      label: "Newsletter CTA",
      description:
        "Conversion newsletter sign-up with heading/body, email field, submit with submitting/success/error states, and a privacy line.",
      kind: "block",
      blockType: "newsletter-cta",
      importPath,
      routeHref: "/ui-primitives/marketing/newsletter-cta",
      tags: ["newsletter", "cta", "signup"],
      status: "improved",
    },
    {
      key: "marketing/footer-megamap",
      family: "marketing",
      name: "FooterMegamap",
      label: "Footer megamap",
      description:
        "Full site footer with brand block, optional region selector, multi-column sitemap nav, contact details, social links, and a legal bar.",
      kind: "block",
      blockType: "footer-megamap",
      importPath,
      routeHref: "/ui-primitives/marketing/footer-megamap",
      tags: ["footer", "navigation", "sitemap"],
      status: "improved",
    },
    {
      key: "marketing/process-steps",
      family: "marketing",
      name: "ProcessSteps",
      label: "Process steps",
      description:
        "Ordered process-steps list (3-5) connected by a line; each step has a numbered badge, icon, title, body, and staggered reveal.",
      kind: "block",
      blockType: "process-steps",
      importPath,
      routeHref: "/ui-primitives/marketing/process-steps",
      tags: ["process", "steps", "onboarding"],
      status: "improved",
    },
    {
      key: "marketing/cookie-banner",
      family: "marketing",
      name: "CookieBanner",
      label: "Cookie banner",
      description:
        "Dismissible cookie-consent banner with optional kicker, heading, body, and manage/accept actions that hide on accept.",
      kind: "primitive",
      importPath,
      routeHref: "/ui-primitives/marketing/cookie-banner",
      tags: ["cookie", "consent", "compliance"],
      status: "improved",
    },
    {
      key: "marketing/floating-chat-launcher",
      family: "marketing",
      name: "FloatingChatLauncher",
      label: "Floating chat launcher",
      description:
        "Floating chat launcher with pulse ring and unread badge that toggles an open preview card (heading, body, custom content).",
      kind: "primitive",
      importPath,
      routeHref: "/ui-primitives/marketing/floating-chat",
      tags: ["chat", "launcher", "engagement"],
      status: "improved",
    },
    {
      key: "marketing/sticky-cta-bar",
      family: "marketing",
      name: "StickyCtaBar",
      label: "Sticky CTA bar",
      description:
        "Scroll-reactive sticky CTA bar (top or bottom) with message, optional badge, and actions; auto-hides on scroll down, respects reduced motion.",
      kind: "primitive",
      importPath,
      routeHref: "/ui-primitives/marketing/sticky-cta-bar",
      tags: ["cta", "sticky", "scroll"],
      status: "improved",
    },
  ],
}

export default manifest
