import type { PrimitiveFamilyManifest } from "../types"

const manifest: PrimitiveFamilyManifest = {
  family: "section-blocks",
  title: "Section blocks",
  group: "Marketing",
  summary:
    "Curated section-library compositions exposed as CMS section blocks: heroes, services, trust, gallery, CTA, pricing, testimonials, promo, and contact.",
  entries: [
    {
      key: "section-blocks/website-hero",
      family: "section-blocks",
      name: "WebsiteHeroSection",
      label: "Website hero",
      description:
        "Top-of-page brand hero — display headline, dual metallic CTA, trust strip, and a carbon-fibre workshop-status panel.",
      kind: "block",
      blockType: "website-hero",
      importPath: "@/app/ui-primitives/section-library/web/website-hero/website-hero-section",
      routeHref: "/ui-primitives/section-library/web",
      tags: ["hero", "landing", "brand", "cta"],
      status: "captured",
    },
    {
      key: "section-blocks/video-hero",
      family: "section-blocks",
      name: "VideoHeroSection",
      label: "Video hero",
      description:
        "Full-bleed cinematic looping video hero with poster fallback, headline, subhead, and a metallic primary CTA.",
      kind: "block",
      blockType: "video-hero",
      importPath: "@/app/ui-primitives/section-library/content/video-hero-section",
      routeHref: "/ui-primitives/section-library/content",
      tags: ["video", "hero", "landing", "media"],
      status: "captured",
    },
    {
      key: "section-blocks/service-overview",
      family: "section-blocks",
      name: "ServiceOverviewSection",
      label: "Service overview",
      description:
        "Grid of core workshop services with icons, descriptions, and per-card deep links. 2-6 cards, 2/3/4 columns.",
      kind: "block",
      blockType: "service-overview",
      importPath: "@/app/ui-primitives/section-library/web/service-overview/service-overview-section",
      routeHref: "/ui-primitives/section-library/web",
      tags: ["services", "feature-grid", "overview"],
      status: "captured",
    },
    {
      key: "section-blocks/workshop-trust",
      family: "section-blocks",
      name: "WorkshopTrustSection",
      label: "Workshop trust",
      description:
        "Social-proof section — a masonry testimonial wall with star ratings plus a supplier brand-mark logo cloud.",
      kind: "block",
      blockType: "workshop-trust",
      importPath: "@/app/ui-primitives/section-library/web/workshop-trust/workshop-trust-section",
      routeHref: "/ui-primitives/section-library/web",
      tags: ["trust", "testimonials", "social-proof", "logos"],
      status: "captured",
    },
    {
      key: "section-blocks/before-after-gallery",
      family: "section-blocks",
      name: "BeforeAfterGallery",
      label: "Before / after gallery",
      description:
        "Grid of job cards that toggle between the stock photo and the finished install, with an optional result chip.",
      kind: "block",
      blockType: "before-after-gallery",
      importPath: "@/app/ui-primitives/section-library/marketing/sections/before-after-gallery",
      routeHref: "/ui-primitives/section-library/marketing",
      tags: ["gallery", "before-after", "proof"],
      status: "captured",
    },
    {
      key: "section-blocks/section-cta",
      family: "section-blocks",
      name: "CtaSection",
      label: "CTA banner",
      description:
        "High-emphasis booking CTA with a metallic-red primary action, carbon outline secondary, and a trust assurance row.",
      kind: "block",
      blockType: "section-cta",
      importPath: "@/app/ui-primitives/section-library/marketing/sections/cta-section",
      routeHref: "/ui-primitives/section-library/marketing",
      tags: ["cta", "conversion", "booking"],
      status: "captured",
    },
    {
      key: "section-blocks/pricing-service",
      family: "section-blocks",
      name: "PricingServiceSection",
      label: "Pricing & service",
      description:
        "Service-tier comparison table with pricing CTAs above an always-included feature grid of guarantees.",
      kind: "block",
      blockType: "pricing-service",
      importPath: "@/app/ui-primitives/section-library/marketing/sections/pricing-service-section",
      routeHref: "/ui-primitives/section-library/marketing",
      tags: ["pricing", "service", "comparison", "conversion"],
      status: "captured",
    },
    {
      key: "section-blocks/testimonials-showcase",
      family: "section-blocks",
      name: "TestimonialsSection",
      label: "Testimonials showcase",
      description:
        "Aggregate review summary (rating, breakdown, sentiment donut, trend) beside a masonry wall of customer quotes.",
      kind: "block",
      blockType: "testimonials-showcase",
      importPath: "@/app/ui-primitives/section-library/marketing/sections/testimonials-section",
      routeHref: "/ui-primitives/section-library/marketing",
      tags: ["testimonials", "reviews", "ratings", "social-proof"],
      status: "captured",
    },
    {
      key: "section-blocks/promo-campaign",
      family: "section-blocks",
      name: "PromoCampaignSection",
      label: "Promo campaign",
      description:
        "Time-boxed offer banner with a metallic CTA, a count-up stat row, and a product feature spotlight.",
      kind: "block",
      blockType: "promo-campaign",
      importPath: "@/app/ui-primitives/section-library/marketing/sections/promo-campaign-section",
      routeHref: "/ui-primitives/section-library/marketing",
      tags: ["promo", "campaign", "offer", "conversion"],
      status: "captured",
    },
    {
      key: "section-blocks/contact-enquiry",
      family: "section-blocks",
      name: "ContactEnquirySection",
      label: "Contact & enquiry",
      description:
        "Contact section — workshop details plus the enquiry form posting to /api/enquiries.",
      kind: "block",
      blockType: "contact-enquiry",
      importPath: "@/app/ui-primitives/section-library/content/contact-enquiry-section",
      routeHref: "/ui-primitives/section-library/content",
      tags: ["contact", "enquiry", "form", "lead"],
      status: "captured",
    },
  ],
}

export default manifest
