import type { PrimitiveFamilyManifest } from "../types"

const manifest: PrimitiveFamilyManifest = {
  family: "torque",
  title: "Torque",
  group: "AI",
  summary:
    "Twenty-two routed Torque business-assistant surfaces for Oak Flats Muffler Men: owner and workshop command centres, chat, activity, approvals, auth, CMS editing, command palette, analytics, channels, file browser, logs, mobile shell, model management, notifications, profile, scheduled jobs, app states, web terminal, social composer/calendar, and workspace settings. Each route composes existing UI primitives into a customer-facing assistant surface.",
  entries: [
    {
      key: "torque/owner-dashboard",
      family: "torque",
      name: "OwnerDashboardPage",
      label: "Owner command centre",
      description:
        "Owner cockpit combining workshop KPIs, bookings, revenue, lead mix, social and SEO health, and recent Torque activity.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/owner-dashboard/page",
      routeHref: "/ui-primitives/torque/owner-dashboard",
      tags: ["assistant", "dashboard", "owner", "workshop"],
      status: "captured",
    },
    {
      key: "torque/workshop-ops",
      family: "torque",
      name: "WorkshopOpsBoardPage",
      label: "Workshop operations board",
      description:
        "Shop-floor command surface for jobs by bay, quote-to-job pipeline, technician allocation, live bay occupancy, and revenue.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/workshop-ops/page",
      routeHref: "/ui-primitives/torque/workshop-ops",
      tags: ["assistant", "operations", "jobs", "workshop"],
      status: "captured",
    },
    {
      key: "torque/torque-chat",
      family: "torque",
      name: "TorqueChatPage",
      label: "Torque assistant chat",
      description:
        "Customer-facing assistant chat where the owner asks Torque to draft content, social posts, and booking calls-to-action.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/torque-chat/page",
      routeHref: "/ui-primitives/torque/torque-chat",
      tags: ["assistant", "chat", "conversation", "marketing"],
      status: "captured",
    },
    {
      key: "torque/agent-activity",
      family: "torque",
      name: "TorqueAgentActivityPage",
      label: "Activity and run feed",
      description:
        "Live activity surface showing Torque's customer enquiries, quote drafts, booking work, run trace, in-progress job board, and daily cost.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/agent-activity/page",
      routeHref: "/ui-primitives/torque/agent-activity",
      tags: ["assistant", "activity", "run-feed", "observability"],
      status: "captured",
    },
    {
      key: "torque/approval-gate",
      family: "torque",
      name: "TorqueApprovalGatePage",
      label: "Approval gate",
      description:
        "Safety surface that holds customer, live-site, and deployment actions for owner review with preview, diff, risk flags, and typed confirmation.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/approval-gate/page",
      routeHref: "/ui-primitives/torque/approval-gate",
      tags: ["assistant", "approval", "safety", "risk"],
      status: "captured",
    },
    {
      key: "torque/auth",
      family: "torque",
      name: "TorqueAuthPage",
      label: "Sign in and sign up",
      description:
        "Torque access surface with split branded layout, OAuth, signup wizard, password strength, and six-digit verification.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/auth/page",
      routeHref: "/ui-primitives/torque/auth",
      tags: ["assistant", "auth", "sign-in", "onboarding"],
      status: "captured",
    },
    {
      key: "torque/cms-editor",
      family: "torque",
      name: "CmsEditorPage",
      label: "CMS page editor",
      description:
        "Owner-facing page-builder surface with page tree, drag-and-drop canvas, slot inspector, block library, review, and publish flow.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/cms-editor/page",
      routeHref: "/ui-primitives/torque/cms-editor",
      tags: ["assistant", "cms", "page-builder", "publishing"],
      status: "captured",
    },
    {
      key: "torque/command-palette",
      family: "torque",
      name: "CommandPalettePage",
      label: "Command palette",
      description:
        "Spotlight-style Torque command palette with grouped quick actions, recent runs, suggestions, shortcut hints, and global keyboard open state.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/command-palette/page",
      routeHref: "/ui-primitives/torque/command-palette",
      tags: ["assistant", "command-palette", "quick-actions", "keyboard"],
      status: "captured",
    },
    {
      key: "torque/channels",
      family: "torque",
      name: "ChannelsPage",
      label: "Connected channels",
      description:
        "Connected-channel console for Telegram, website chat, SMS, email, and Discord health, setup, routing rules, and audit trail.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/channels/page",
      routeHref: "/ui-primitives/torque/channels",
      tags: ["assistant", "channels", "messaging", "integrations"],
      status: "captured",
    },
    {
      key: "torque/analytics",
      family: "torque",
      name: "BusinessAnalyticsPage",
      label: "Business analytics",
      description:
        "Business analytics panel for revenue, bookings, local SEO, social reach, top pages, and Torque operating cost.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/analytics/page",
      routeHref: "/ui-primitives/torque/analytics",
      tags: ["assistant", "analytics", "revenue", "seo"],
      status: "captured",
    },
    {
      key: "torque/file-browser",
      family: "torque",
      name: "FileBrowserPage",
      label: "File browser",
      description:
        "Workshop asset-library surface with folder navigation, grid/list views, selection, preview, upload, versions, and destructive-action affordances.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/file-browser/page",
      routeHref: "/ui-primitives/torque/file-browser",
      tags: ["assistant", "files", "assets", "media"],
      status: "captured",
    },
    {
      key: "torque/logs-viewer",
      family: "torque",
      name: "LogsViewerPage",
      label: "Logs viewer",
      description:
        "Structured platform-log stream for Torque with search, level/source filters, live-tail controls, expandable rows, and incident context.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/logs-viewer/page",
      routeHref: "/ui-primitives/torque/logs-viewer",
      tags: ["assistant", "logs", "observability", "debugging"],
      status: "captured",
    },
    {
      key: "torque/model-manager",
      family: "torque",
      name: "ModelManagerPage",
      label: "Model manager",
      description:
        "AI model-management panel for Torque defaults, model availability, per-route token usage, cost charts, comparison data, and budget posture.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/model-manager/page",
      routeHref: "/ui-primitives/torque/model-manager",
      tags: ["assistant", "models", "usage", "ai"],
      status: "captured",
    },
    {
      key: "torque/mobile-shell",
      family: "torque",
      name: "TorqueMobileShellPage",
      label: "Torque on mobile",
      description:
        "Mobile Torque composition with app bar, bottom navigation, FAB, drawer, bottom sheet, chat, and quote approval.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/mobile-shell/page",
      routeHref: "/ui-primitives/torque/mobile-shell",
      tags: ["assistant", "mobile", "shell", "approval"],
      status: "captured",
    },
    {
      key: "torque/notifications",
      family: "torque",
      name: "TorqueNotificationsPage",
      label: "Notifications inbox",
      description:
        "Grouped Torque inbox for sign-off, system, activity, social, and SEO alerts with read, dismiss, and mark-all-read affordances.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/notifications/page",
      routeHref: "/ui-primitives/torque/notifications",
      tags: ["assistant", "notifications", "inbox", "alerts"],
      status: "captured",
    },
    {
      key: "torque/profile",
      family: "torque",
      name: "ProfilePage",
      label: "User profile",
      description:
        "Owner profile screen for identity, plan, activity summary, notification preferences, devices, and recent actions.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/profile/page",
      routeHref: "/ui-primitives/torque/profile",
      tags: ["assistant", "profile", "account", "activity"],
      status: "captured",
    },
    {
      key: "torque/scheduled-jobs",
      family: "torque",
      name: "ScheduledJobsPage",
      label: "Scheduled jobs",
      description:
        "Automation console for scheduled Torque jobs with cron detail, next run, last status, run history, trace, and enable/disable controls.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/scheduled-jobs/page",
      routeHref: "/ui-primitives/torque/scheduled-jobs",
      tags: ["assistant", "automation", "cron", "jobs"],
      status: "captured",
    },
    {
      key: "torque/web-terminal",
      family: "torque",
      name: "TorqueWebTerminalPage",
      label: "Web terminal",
      description:
        "Safe read-only operator console for Torque service sessions, scrollback transcripts, session metrics, recent commands, and run status.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/web-terminal/page",
      routeHref: "/ui-primitives/torque/web-terminal",
      tags: ["assistant", "terminal", "operator", "observability"],
      status: "captured",
    },
    {
      key: "torque/states-overview",
      family: "torque",
      name: "StatesOverviewPage",
      label: "App states",
      description:
        "Full-surface Torque app states for empty queues, loading, server faults, offline, maintenance, and confirmed success.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/states-overview/page",
      routeHref: "/ui-primitives/torque/states-overview",
      tags: ["assistant", "states", "empty", "offline"],
      status: "captured",
    },
    {
      key: "torque/settings",
      family: "torque",
      name: "SettingsPage",
      label: "Settings and workspace",
      description:
        "Workspace settings surface for profile, plan, crew roles, connected tools, notifications, API access, and destructive actions.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/settings/page",
      routeHref: "/ui-primitives/torque/settings",
      tags: ["assistant", "settings", "workspace", "integrations"],
      status: "captured",
    },
    {
      key: "torque/social-calendar",
      family: "torque",
      name: "SocialCalendarPage",
      label: "Social content calendar",
      description:
        "Monthly social planning surface with scheduled posts, channel status, campaign filters, upcoming queue, and owner approval gate.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/social-calendar/page",
      routeHref: "/ui-primitives/torque/social-calendar",
      tags: ["assistant", "social", "calendar", "approvals"],
      status: "captured",
    },
    {
      key: "torque/social-composer",
      family: "torque",
      name: "TorqueSocialComposerPage",
      label: "Social post composer",
      description:
        "Marketing composer for Torque-drafted captions, generated media previews, per-channel layouts, scheduling, brand checks, and approval controls.",
      kind: "scene",
      importPath: "@/app/ui-primitives/torque/social-composer/page",
      routeHref: "/ui-primitives/torque/social-composer",
      tags: ["assistant", "social", "composer", "marketing"],
      status: "captured",
    },
  ],
}

export default manifest
