import type { PrimitiveEntry, PrimitiveFamilyManifest } from "../types"

const existingFontEntries: readonly PrimitiveEntry[] = [
  {
    key: "typography/font-anton",
    family: "typography",
    name: "FontAnton",
    label: "Anton",
    description: "Anton single-cut industrial display specimen tile with per-letter staggered rise, body/caption copy, and a letter-spacing/case weight scale.",
    kind: "primitive",
    importPath: "@/app/ui-primitives/components/typography",
    routeHref: "/ui-primitives/typography#section-anton",
    tags: ["display", "specimen", "hero"],
    status: "captured",
  },
  {
    key: "typography/font-big-shoulders",
    family: "typography",
    name: "FontBigShoulders",
    label: "Big Shoulders Inline",
    description: "Big Shoulders Inline display specimen tile with coach-line inline rule and a 400/700/900 weight scale for signage and livery callouts.",
    kind: "primitive",
    importPath: "@/app/ui-primitives/components/typography",
    routeHref: "/ui-primitives/typography#section-bigshoulders",
    tags: ["display", "specimen", "signage"],
    status: "captured",
  },
  {
    key: "typography/font-bebas",
    family: "typography",
    name: "FontBebas",
    label: "Bebas Neue",
    description: "Bebas Neue condensed display specimen tile rendering a looping marquee banner of workshop phrases plus a tracking/marquee weight scale.",
    kind: "primitive",
    importPath: "@/app/ui-primitives/components/typography",
    routeHref: "/ui-primitives/typography#section-bebas",
    tags: ["display", "specimen", "marquee"],
    status: "captured",
  },
  {
    key: "typography/font-space-grotesk",
    family: "typography",
    name: "FontSpaceGrotesk",
    label: "Space Grotesk",
    description: "Space Grotesk sans specimen tile with a typewriter display shell and a 300-to-700 weight scale.",
    kind: "primitive",
    importPath: "@/app/ui-primitives/components/typography",
    routeHref: "/ui-primitives/typography#section-space-grotesk",
    tags: ["sans", "specimen", "body"],
    status: "captured",
  },
  {
    key: "typography/font-fraunces",
    family: "typography",
    name: "FontFraunces",
    label: "Fraunces",
    description: "Fraunces variable-serif specimen tile demonstrating wght and opsz axes across an editorial weight/optical-size scale.",
    kind: "primitive",
    importPath: "@/app/ui-primitives/components/typography",
    routeHref: "/ui-primitives/typography#section-fraunces",
    tags: ["serif", "variable", "editorial"],
    status: "captured",
  },
  {
    key: "typography/font-major-mono",
    family: "typography",
    name: "FontMajorMono",
    label: "Major Mono Display",
    description: "Major Mono Display specimen tile with a requestAnimationFrame cipher-scramble reveal for VIN and serial markers.",
    kind: "primitive",
    importPath: "@/app/ui-primitives/components/typography",
    routeHref: "/ui-primitives/typography#section-major-mono",
    tags: ["mono", "specimen", "scramble"],
    status: "captured",
  },
  {
    key: "typography/font-bricolage",
    family: "typography",
    name: "FontBricolage",
    label: "Bricolage Grotesque",
    description: "Bricolage Grotesque variable-grotesque specimen tile exercising wdth and opsz axes from tight chips to wide headlines.",
    kind: "primitive",
    importPath: "@/app/ui-primitives/components/typography",
    routeHref: "/ui-primitives/typography#section-bricolage",
    tags: ["grotesque", "variable", "specimen"],
    status: "captured",
  },
  {
    key: "typography/font-ibm-mono",
    family: "typography",
    name: "FontIbmMono",
    label: "IBM Plex Mono",
    description: "IBM Plex Mono specimen tile with a scanline-wipe display shell and a 400/600 weight scale for code, logs, and telemetry.",
    kind: "primitive",
    importPath: "@/app/ui-primitives/components/typography",
    routeHref: "/ui-primitives/typography#section-ibm-mono",
    tags: ["mono", "code", "telemetry"],
    status: "captured",
  },
  {
    key: "typography/font-inter-tight",
    family: "typography",
    name: "FontInterTight",
    label: "Inter Tight",
    description: "Inter Tight variable-sans specimen tile with a multi-stop gradient color-sweep heading and a 300-to-900 weight scale.",
    kind: "primitive",
    importPath: "@/app/ui-primitives/components/typography",
    routeHref: "/ui-primitives/typography#section-inter-tight",
    tags: ["sans", "variable", "marketing"],
    status: "captured",
  },
  {
    key: "typography/font-cormorant",
    family: "typography",
    name: "FontCormorant",
    label: "Cormorant Garamond",
    description: "Cormorant Garamond serif-revival specimen tile with regular/bold and roman/italic scale for heritage and editorial copy.",
    kind: "primitive",
    importPath: "@/app/ui-primitives/components/typography",
    routeHref: "/ui-primitives/typography#section-cormorant",
    tags: ["serif", "italic", "editorial"],
    status: "captured",
  },
]

const addedFontOptionEntries: readonly PrimitiveEntry[] = [
  ["archivo-black", "Archivo Black", "Heavy industrial display option for hero lockups and impact cards.", ["display", "font-option", "hero"]],
  ["barlow-condensed", "Barlow Condensed", "Condensed service-board option for schedules, bay lists, and dense headings.", ["condensed", "font-option", "operations"]],
  ["teko", "Teko", "Tall motorsport display option for dyno, status, and performance headings.", ["condensed", "font-option", "performance"]],
  ["chakra-petch", "Chakra Petch", "Technical square sans option for diagnostics, controls, and telemetry UI.", ["technical", "font-option", "telemetry"]],
  ["saira-condensed", "Saira Condensed", "Multi-weight condensed option for dashboards, rails, and production boards.", ["condensed", "font-option", "dashboard"]],
  ["dm-serif-display", "DM Serif Display", "Editorial serif option for craft notes, heritage copy, and premium print moments.", ["serif", "font-option", "editorial"]],
  ["kode-mono", "Kode Mono", "Variable mono option for codes, job IDs, and compact technical panels.", ["mono", "font-option", "code"]],
  ["source-code-pro", "Source Code Pro", "Readable technical mono option for logs, scripts, and data-heavy surfaces.", ["mono", "font-option", "code"]],
].map(([id, label, description, tags]) => ({
  key: `typography/font-${id}`,
  family: "typography",
  name: "KineticText",
  label,
  description,
  kind: "primitive",
  importPath: "@/app/ui-primitives/components/typography",
  routeHref: "/ui-primitives/typography#section-font-options",
  tags,
  status: "captured",
})) as readonly PrimitiveEntry[]

const roleEntries: readonly PrimitiveEntry[] = [
  ["display", "RoleDisplay", "Display role", "Production display role component for hero mastheads, signage panels, and campaign leads."],
  ["h1", "RoleH1", "Heading 1 role", "Production H1 role component for primary page titles and full-screen workflow headers."],
  ["h2", "RoleH2", "Heading 2 role", "Production H2 role component for major sections and dashboard surface titles."],
  ["h3", "RoleH3", "Heading 3 role", "Production H3 role component for panel groups, card clusters, and sub-route titles."],
  ["h4", "RoleH4", "Heading 4 role", "Production H4 role component for compact card titles and toolbar section labels."],
  ["h5", "RoleH5", "Heading 5 role", "Production H5 role component for small card headers, list groups, and dense inspectors."],
  ["h6", "RoleH6", "Heading 6 role", "Production H6 role component for micro-section headers and repeated table groups."],
  ["body-lead", "RoleBodyLead", "Body lead role", "Production lead-body role component for intro paragraphs and workflow explainers."],
  ["body-base", "RoleBodyBase", "Body base role", "Production base-body role component for default UI copy, cards, forms, and blocks."],
  ["body-small", "RoleBodySmall", "Body small role", "Production small-body role component for secondary descriptions and dense cards."],
  ["caption", "RoleCaption", "Caption role", "Production caption role component for metadata, timestamps, and media notes."],
  ["eyebrow", "RoleEyebrow", "Eyebrow role", "Production eyebrow role component for uppercase section labels and board markers."],
  ["label", "RoleLabel", "Label role", "Production label role component for controls, chips, badges, and filters."],
  ["mono", "RoleMono", "Mono role", "Production mono role component for codes, logs, routes, and technical readouts."],
  ["numeric", "RoleNumeric", "Numeric role", "Production numeric role component for tabular counters, prices, percentages, and KPIs."],
].map(([id, name, label, description]) => ({
  key: `typography/role-${id}`,
  family: "typography",
  name,
  label,
  description,
  kind: "primitive",
  importPath: "@/app/ui-primitives/components/typography",
  routeHref: id === "display" || String(id).startsWith("h")
    ? "/ui-primitives/typography#section-heading-roles"
    : "/ui-primitives/typography#section-body-roles",
  tags: ["role", "type-scale", "production-file"],
  status: "captured",
})) as readonly PrimitiveEntry[]

const manifest: PrimitiveFamilyManifest = {
  family: "typography",
  title: "Typography",
  group: "Foundations",
  summary: "Eighteen font options, production typography role components, complete heading/body size scales, spacing rhythm, and the KineticText primitive for animated brand type.",
  entries: [
    ...existingFontEntries,
    ...addedFontOptionEntries,
    ...roleEntries,
    {
      key: "typography/kinetic-text",
      family: "typography",
      name: "KineticText",
      label: "Kinetic text",
      description: "Client primitive that renders children in a chosen fontId with a kinetic motion and size scale while keeping accessible text and reduced-motion handling.",
      kind: "primitive",
      importPath: "@/app/ui-primitives/components/typography",
      routeHref: "/ui-primitives/typography#section-kinetic",
      tags: ["kinetic", "motion", "animated-text"],
      status: "captured",
    },
  ],
}

export default manifest
