/**
 * Color token controls. Themed (light/dark) unless noted.
 * Defaults are the literal dark (canonical) values; `lightDefault` carries the
 * light-theme override where the token differs between themes.
 */
import type { TokenGroupCatalog } from "../types";

export const COLOR_CATALOG: TokenGroupCatalog = {
  group: "Color",
  label: "Color",
  description:
    "Brand, text, surface, line, field, and accent colors. Themed light/dark.",
  tokens: [
    {
      token: "--primitive-canvas",
      label: "Canvas",
      description: "Base background color behind the whole dashboard.",
      group: "Color",
      control: { kind: "color" },
      default: "#050508",
      lightDefault: "#f2f5f4",
      scope: "themed",
      affects: ["canvas", "all"],
    },
    {
      token: "--primitive-red",
      label: "Brand red",
      description: "Primary brand red used for CTAs, accents, and meters.",
      group: "Color",
      control: { kind: "color" },
      default: "#e62028",
      lightDefault: "#d63a26",
      scope: "themed",
      affects: ["buttons", "meters", "controls", "all"],
    },
    {
      token: "--primitive-red-dark",
      label: "Brand red (dark)",
      description: "Deep red used for the bottom of metallic-red gradients and hovers.",
      group: "Color",
      control: { kind: "color" },
      default: "#a8141a",
      lightDefault: "#962417",
      scope: "themed",
      affects: ["buttons", "all"],
    },
    {
      token: "--primitive-amber",
      label: "Accent amber",
      description: "Gold/amber accent used for highlights and the hover button state.",
      group: "Color",
      control: { kind: "color" },
      default: "#ffc14f",
      lightDefault: "#d96f19",
      scope: "themed",
      affects: ["buttons", "meters", "all"],
    },
    {
      token: "--primitive-teal",
      label: "Teal",
      description: "Cool accent / focus-ring source and meter mid-stop.",
      group: "Color",
      control: { kind: "color" },
      default: "#40bcff",
      lightDefault: "#087f83",
      scope: "themed",
      affects: ["meters", "focus", "all"],
    },
    {
      token: "--primitive-green",
      label: "Green",
      description: "Positive / success accent.",
      group: "Color",
      control: { kind: "color" },
      default: "#37d67a",
      lightDefault: "#147853",
      scope: "themed",
      affects: ["all"],
    },
    {
      token: "--primitive-body",
      label: "Body text",
      description: "Default body / paragraph text color.",
      group: "Color",
      control: { kind: "color" },
      default: "#c7c9d0",
      lightDefault: "#334147",
      scope: "themed",
      affects: ["typography"],
    },
    {
      token: "--primitive-muted",
      label: "Muted text",
      description: "Secondary / muted text and labels.",
      group: "Color",
      control: { kind: "color" },
      default: "#868b98",
      lightDefault: "#68777e",
      scope: "themed",
      affects: ["typography"],
    },
    {
      token: "--primitive-text-strong",
      label: "Strong text",
      description: "High-contrast headings and emphasized text.",
      group: "Color",
      control: { kind: "color" },
      default: "#ffffff",
      lightDefault: "#172027",
      scope: "themed",
      affects: ["typography"],
    },
    {
      token: "--primitive-text-on-accent",
      label: "Text on accent",
      description: "Text color when sitting on a red/amber accent fill.",
      group: "Color",
      control: { kind: "color" },
      default: "#ffffff",
      lightDefault: "#ffffff",
      scope: "themed",
      affects: ["buttons", "typography"],
    },
    {
      token: "--primitive-panel",
      label: "Panel",
      description: "Translucent panel surface (cards, popovers).",
      group: "Color",
      control: { kind: "color", supportsAlpha: true },
      default: "rgba(16, 16, 22, 0.82)",
      lightDefault: "rgba(249, 251, 250, 0.78)",
      scope: "themed",
      affects: ["panels", "cards"],
    },
    {
      token: "--primitive-panel-strong",
      label: "Panel (strong)",
      description: "More opaque panel surface for elevated layers.",
      group: "Color",
      control: { kind: "color", supportsAlpha: true },
      default: "rgba(23, 24, 32, 0.96)",
      lightDefault: "rgba(255, 255, 255, 0.96)",
      scope: "themed",
      affects: ["panels", "cards"],
    },
    {
      token: "--primitive-surface-3",
      label: "Surface 3",
      description: "Tertiary translucent surface tint.",
      group: "Color",
      control: { kind: "color", supportsAlpha: true },
      default: "rgba(255, 255, 255, 0.07)",
      lightDefault: "rgba(255, 255, 255, 0.72)",
      scope: "themed",
      affects: ["panels"],
    },
    {
      token: "--primitive-surface-hover",
      label: "Surface hover",
      description: "Hover tint applied over surfaces.",
      group: "Color",
      control: { kind: "color", supportsAlpha: true },
      default: "rgba(255, 255, 255, 0.11)",
      lightDefault: "rgba(255, 255, 255, 0.92)",
      scope: "themed",
      affects: ["panels", "controls"],
    },
    {
      token: "--primitive-line",
      label: "Hairline",
      description: "Default 1px border / divider color.",
      group: "Color",
      control: { kind: "color", supportsAlpha: true },
      default: "rgba(255, 255, 255, 0.13)",
      lightDefault: "rgba(35, 45, 51, 0.15)",
      scope: "themed",
      affects: ["panels", "cards", "fields", "nav"],
    },
    {
      token: "--primitive-line-strong",
      label: "Hairline (strong)",
      description: "Stronger border for emphasized edges.",
      group: "Color",
      control: { kind: "color", supportsAlpha: true },
      default: "rgba(255, 255, 255, 0.22)",
      lightDefault: "rgba(35, 45, 51, 0.27)",
      scope: "themed",
      affects: ["panels", "buttons"],
    },
    {
      token: "--primitive-line-muted",
      label: "Hairline (muted)",
      description: "Faintest divider for low-emphasis splits.",
      group: "Color",
      control: { kind: "color", supportsAlpha: true },
      default: "rgba(255, 255, 255, 0.08)",
      lightDefault: "rgba(35, 45, 51, 0.09)",
      scope: "themed",
      affects: ["panels"],
    },
    {
      token: "--primitive-recessed",
      label: "Recessed",
      description: "Inset / recessed dark fill (wells, tracks).",
      group: "Color",
      control: { kind: "color", supportsAlpha: true },
      default: "rgba(0, 0, 0, 0.32)",
      lightDefault: "rgba(211, 222, 221, 0.62)",
      scope: "themed",
      affects: ["controls", "fields"],
    },
    {
      token: "--primitive-overlay",
      label: "Overlay scrim",
      description: "Dim scrim behind modals / drawers.",
      group: "Color",
      control: { kind: "color", supportsAlpha: true },
      default: "rgba(0, 0, 0, 0.48)",
      lightDefault: "rgba(242, 245, 244, 0.8)",
      scope: "themed",
      affects: ["overlays"],
    },
    {
      token: "--primitive-media-overlay",
      label: "Media overlay",
      description: "Darken layer over imagery for legible captions.",
      group: "Color",
      control: { kind: "color", supportsAlpha: true },
      default: "rgba(0, 0, 0, 0.62)",
      lightDefault: "rgba(12, 18, 22, 0.48)",
      scope: "themed",
      affects: ["media", "overlays"],
    },
    {
      token: "--primitive-code-bg",
      label: "Code background",
      description: "Background fill for code blocks.",
      group: "Color",
      control: { kind: "color", supportsAlpha: true },
      default: "rgba(8, 9, 14, 0.92)",
      lightDefault: "rgba(247, 249, 247, 0.88)",
      scope: "themed",
      affects: ["code"],
    },
    {
      token: "--primitive-code-fg",
      label: "Code text",
      description: "Foreground text color in code blocks.",
      group: "Color",
      control: { kind: "color" },
      default: "#f6f6f8",
      lightDefault: "#172027",
      scope: "themed",
      affects: ["code"],
    },
    {
      token: "--primitive-meter-track",
      label: "Meter track",
      description: "Empty-track color behind meters / progress bars.",
      group: "Color",
      control: { kind: "color", supportsAlpha: true },
      default: "rgba(255, 255, 255, 0.1)",
      lightDefault: "rgba(35, 45, 51, 0.13)",
      scope: "themed",
      affects: ["meters"],
    },
  ],
};
