/**
 * Component-DNA token controls — Button, Card, Form, and Nav groups.
 *
 * Most of these reference other primitive tokens (e.g. the button bg points at
 * the metallic gradient). The control panel can re-point them or edit the
 * resolved value; either way the source of truth stays the central tokens.
 */
import type { SelectOption, TokenGroupCatalog } from "../types";

const RADIUS_REF_OPTIONS: readonly SelectOption[] = [
  { label: "None", value: "var(--primitive-radius-none)" },
  { label: "XS (2px)", value: "var(--primitive-radius-xs)" },
  { label: "SM (4px)", value: "var(--primitive-radius-sm)" },
  { label: "MD (8px)", value: "var(--primitive-radius-md)" },
  { label: "LG (12px)", value: "var(--primitive-radius-lg)" },
  { label: "XL (16px)", value: "var(--primitive-radius-xl)" },
  { label: "Pill", value: "var(--primitive-radius-pill)" },
];

export const BUTTON_CATALOG: TokenGroupCatalog = {
  group: "Button",
  label: "Button DNA",
  description:
    "Primary (metallic-red) + secondary (carbon) button background, foreground, shadow, radius.",
  tokens: [
    {
      token: "--primitive-btn-radius",
      label: "Button radius",
      description: "Corner radius for all buttons.",
      group: "Button",
      control: { kind: "select", options: RADIUS_REF_OPTIONS },
      default: "var(--primitive-radius-sm)",
      scope: "shared",
      affects: ["buttons"],
    },
    {
      token: "--primitive-size-ui-2xs",
      label: "UI chrome 2xs",
      description: "Extra-compact toolbar and table chrome button height.",
      group: "Button",
      control: { kind: "slider", min: 20, max: 40, step: 1, unit: "px" },
      default: "24px",
      scope: "shared",
      affects: ["buttons", "controls"],
    },
    {
      token: "--primitive-size-ui-xs",
      label: "UI chrome xs",
      description: "Compact toolbar and table chrome button height.",
      group: "Button",
      control: { kind: "slider", min: 22, max: 44, step: 1, unit: "px" },
      default: "28px",
      scope: "shared",
      affects: ["buttons", "controls"],
    },
    {
      token: "--primitive-size-ui-sm",
      label: "UI chrome sm",
      description: "Small route chrome button height.",
      group: "Button",
      control: { kind: "slider", min: 24, max: 48, step: 1, unit: "px" },
      default: "32px",
      scope: "shared",
      affects: ["buttons", "controls"],
    },
    {
      token: "--primitive-size-ui-md",
      label: "UI chrome md",
      description: "Default route chrome button height.",
      group: "Button",
      control: { kind: "slider", min: 28, max: 52, step: 1, unit: "px" },
      default: "36px",
      scope: "shared",
      affects: ["buttons", "controls"],
    },
    {
      token: "--primitive-size-command-sm",
      label: "Command button sm",
      description: "Small command/action button height.",
      group: "Button",
      control: { kind: "slider", min: 36, max: 64, step: 1, unit: "px" },
      default: "44px",
      scope: "shared",
      affects: ["buttons", "controls"],
    },
    {
      token: "--primitive-size-command-md",
      label: "Command button md",
      description: "Default command/action button height.",
      group: "Button",
      control: { kind: "slider", min: 40, max: 72, step: 1, unit: "px" },
      default: "48px",
      scope: "shared",
      affects: ["buttons", "controls"],
    },
    {
      token: "--primitive-size-command-lg",
      label: "Command button lg",
      description: "Large command/action button height.",
      group: "Button",
      control: { kind: "slider", min: 44, max: 80, step: 1, unit: "px" },
      default: "56px",
      scope: "shared",
      affects: ["buttons", "controls"],
    },
    {
      token: "--primitive-size-icon-button-xs",
      label: "Icon button xs",
      description: "Extra-compact icon-only button square.",
      group: "Button",
      control: { kind: "slider", min: 20, max: 44, step: 1, unit: "px" },
      default: "24px",
      scope: "shared",
      affects: ["buttons", "icons", "controls"],
    },
    {
      token: "--primitive-size-icon-button-sm",
      label: "Icon button sm",
      description: "Small icon-only button square.",
      group: "Button",
      control: { kind: "slider", min: 22, max: 48, step: 1, unit: "px" },
      default: "28px",
      scope: "shared",
      affects: ["buttons", "icons", "controls"],
    },
    {
      token: "--primitive-size-icon-button-md",
      label: "Icon button md",
      description: "Default icon-only button square.",
      group: "Button",
      control: { kind: "slider", min: 24, max: 56, step: 1, unit: "px" },
      default: "32px",
      scope: "shared",
      affects: ["buttons", "icons", "controls"],
    },
    {
      token: "--primitive-size-icon-button-lg",
      label: "Icon button lg",
      description: "Large icon-only button square.",
      group: "Button",
      control: { kind: "slider", min: 28, max: 60, step: 1, unit: "px" },
      default: "36px",
      scope: "shared",
      affects: ["buttons", "icons", "controls"],
    },
    {
      token: "--primitive-size-icon-button-xl",
      label: "Icon button xl",
      description: "Command-scale icon-only button square.",
      group: "Button",
      control: { kind: "slider", min: 32, max: 68, step: 1, unit: "px" },
      default: "44px",
      scope: "shared",
      affects: ["buttons", "icons", "controls"],
    },
    {
      token: "--primitive-size-pill-sm",
      label: "Pill sm",
      description: "Compact pill, chip, badge, and facet height.",
      group: "Button",
      control: { kind: "slider", min: 20, max: 40, step: 1, unit: "px" },
      default: "24px",
      scope: "shared",
      affects: ["controls"],
    },
    {
      token: "--primitive-size-pill-md",
      label: "Pill md",
      description: "Default pill, chip, badge, and facet height.",
      group: "Button",
      control: { kind: "slider", min: 22, max: 44, step: 1, unit: "px" },
      default: "28px",
      scope: "shared",
      affects: ["controls"],
    },
    {
      token: "--primitive-size-pill-lg",
      label: "Pill lg",
      description: "Large pill, chip, badge, and facet height.",
      group: "Button",
      control: { kind: "slider", min: 24, max: 52, step: 1, unit: "px" },
      default: "32px",
      scope: "shared",
      affects: ["controls"],
    },
    {
      token: "--primitive-btn-primary-bg",
      label: "Primary background",
      description: "Primary button body (metallic-red).",
      group: "Button",
      control: { kind: "color", supportsAlpha: true },
      default: "var(--primitive-metallic-red)",
      scope: "themed",
      affects: ["buttons"],
    },
    {
      token: "--primitive-btn-primary-fg",
      label: "Primary foreground",
      description: "Primary button text color.",
      group: "Button",
      control: { kind: "color" },
      default: "var(--primitive-text-on-accent)",
      scope: "themed",
      affects: ["buttons"],
    },
    {
      token: "--primitive-btn-primary-shadow",
      label: "Primary shadow",
      description: "Clearcoat sheen + drop shadow for primary button.",
      group: "Button",
      control: {
        kind: "select",
        options: [
          {
            label: "Clearcoat (default)",
            value:
              "inset 0 1px 0 rgba(255, 255, 255, 0.34), inset 0 -1px 0 rgba(0, 0, 0, 0.4), 0 10px 24px color-mix(in oklab, var(--primitive-red) 38%, transparent)",
          },
          { label: "Flat", value: "none" },
        ],
      },
      default:
        "inset 0 1px 0 rgba(255, 255, 255, 0.34), inset 0 -1px 0 rgba(0, 0, 0, 0.4), 0 10px 24px color-mix(in oklab, var(--primitive-red) 38%, transparent)",
      scope: "themed",
      affects: ["buttons"],
    },
    {
      token: "--primitive-btn-primary-hover-bg",
      label: "Primary hover background",
      description: "Primary button hover body (metallic-amber).",
      group: "Button",
      control: { kind: "color", supportsAlpha: true },
      default: "var(--primitive-metallic-amber)",
      scope: "themed",
      affects: ["buttons"],
    },
    {
      token: "--primitive-btn-primary-hover-fg",
      label: "Primary hover foreground",
      description: "Primary button hover text color.",
      group: "Button",
      control: { kind: "color" },
      default: "var(--primitive-canvas)",
      scope: "themed",
      affects: ["buttons"],
    },
    {
      token: "--primitive-btn-primary-hover-shadow",
      label: "Primary hover shadow",
      description: "Hover clearcoat sheen + amber drop shadow.",
      group: "Button",
      control: {
        kind: "select",
        options: [
          {
            label: "Clearcoat (default)",
            value:
              "inset 0 1px 0 rgba(255, 255, 255, 0.5), inset 0 -1px 0 rgba(0, 0, 0, 0.4), 0 14px 30px color-mix(in oklab, var(--primitive-amber) 44%, transparent)",
          },
          { label: "Flat", value: "none" },
        ],
      },
      default:
        "inset 0 1px 0 rgba(255, 255, 255, 0.5), inset 0 -1px 0 rgba(0, 0, 0, 0.4), 0 14px 30px color-mix(in oklab, var(--primitive-amber) 44%, transparent)",
      scope: "themed",
      affects: ["buttons"],
    },
    {
      token: "--primitive-btn-secondary-bg",
      label: "Secondary background",
      description: "Secondary / ghost button body (carbon black).",
      group: "Button",
      control: { kind: "color", supportsAlpha: true },
      default: "var(--primitive-metallic-black)",
      scope: "shared",
      affects: ["buttons"],
    },
    {
      token: "--primitive-btn-secondary-fg",
      label: "Secondary foreground",
      description: "Secondary button text color.",
      group: "Button",
      control: { kind: "color" },
      default: "var(--primitive-text-strong)",
      scope: "themed",
      affects: ["buttons"],
    },
    {
      token: "--primitive-btn-secondary-border",
      label: "Secondary border",
      description: "Secondary button border color.",
      group: "Button",
      control: { kind: "color", supportsAlpha: true },
      default: "var(--primitive-line-strong)",
      scope: "themed",
      affects: ["buttons"],
    },
  ],
};

export const CARD_CATALOG: TokenGroupCatalog = {
  group: "Card",
  label: "Card",
  description: "Card background, border, and shadow surfaces.",
  tokens: [
    {
      token: "--primitive-card-bg",
      label: "Card background",
      description: "Card surface fill (defaults to control surface).",
      group: "Card",
      control: { kind: "color", supportsAlpha: true },
      default: "var(--primitive-control-surface)",
      scope: "themed",
      affects: ["cards"],
    },
    {
      token: "--primitive-card-border",
      label: "Card border",
      description: "Card edge color.",
      group: "Card",
      control: { kind: "color", supportsAlpha: true },
      default: "var(--primitive-line)",
      scope: "themed",
      affects: ["cards"],
    },
    {
      token: "--primitive-card-shadow",
      label: "Card shadow",
      description: "Resting card elevation shadow.",
      group: "Card",
      control: {
        kind: "select",
        options: [
          { label: "Surface", value: "var(--primitive-surface-shadow)" },
          { label: "Soft", value: "var(--primitive-shadow-soft)" },
          { label: "None", value: "none" },
        ],
      },
      default: "var(--primitive-surface-shadow)",
      scope: "themed",
      affects: ["cards"],
    },
    {
      token: "--primitive-card-hover-shadow",
      label: "Card hover shadow",
      description: "Card lift shadow on hover.",
      group: "Card",
      control: {
        kind: "select",
        options: [
          { label: "Surface hover", value: "var(--primitive-surface-hover-shadow)" },
          { label: "Deep", value: "var(--primitive-shadow-deep)" },
          { label: "None", value: "none" },
        ],
      },
      default: "var(--primitive-surface-hover-shadow)",
      scope: "themed",
      affects: ["cards"],
    },
    {
      token: "--primitive-card-min-sm",
      label: "Card min sm",
      description: "Small card minimum height.",
      group: "Card",
      control: { kind: "slider", min: 96, max: 260, step: 4, unit: "px" },
      default: "160px",
      scope: "shared",
      affects: ["cards"],
    },
    {
      token: "--primitive-card-min-md",
      label: "Card min md",
      description: "Default card minimum height.",
      group: "Card",
      control: { kind: "slider", min: 140, max: 360, step: 4, unit: "px" },
      default: "220px",
      scope: "shared",
      affects: ["cards"],
    },
    {
      token: "--primitive-card-min-lg",
      label: "Card min lg",
      description: "Large card minimum height.",
      group: "Card",
      control: { kind: "slider", min: 180, max: 520, step: 4, unit: "px" },
      default: "320px",
      scope: "shared",
      affects: ["cards"],
    },
    {
      token: "--primitive-size-icon-well-sm",
      label: "Icon well sm",
      description: "Small icon well for compact cards and dense rows.",
      group: "Card",
      control: { kind: "slider", min: 24, max: 56, step: 1, unit: "px" },
      default: "32px",
      scope: "shared",
      affects: ["cards", "icons"],
    },
    {
      token: "--primitive-size-icon-well-md",
      label: "Icon well md",
      description: "Default icon well for cards, states, and command panels.",
      group: "Card",
      control: { kind: "slider", min: 28, max: 64, step: 1, unit: "px" },
      default: "40px",
      scope: "shared",
      affects: ["cards", "icons"],
    },
    {
      token: "--primitive-size-icon-well-lg",
      label: "Icon well lg",
      description: "Large icon well for section cards and state panels.",
      group: "Card",
      control: { kind: "slider", min: 32, max: 72, step: 1, unit: "px" },
      default: "48px",
      scope: "shared",
      affects: ["cards", "icons"],
    },
    {
      token: "--primitive-media-thumb",
      label: "Media thumb",
      description: "Thumbnail media-frame size for dense rows and galleries.",
      group: "Card",
      control: { kind: "slider", min: 56, max: 180, step: 4, unit: "px" },
      default: "96px",
      scope: "shared",
      affects: ["cards", "media"],
    },
    {
      token: "--primitive-media-card",
      label: "Media card height",
      description: "Default media-frame height inside cards and section previews.",
      group: "Card",
      control: { kind: "slider", min: 96, max: 320, step: 4, unit: "px" },
      default: "168px",
      scope: "shared",
      affects: ["cards", "media"],
    },
    {
      token: "--primitive-media-hero",
      label: "Media hero height",
      description: "Hero media-frame height for full-section patterns.",
      group: "Card",
      control: { kind: "slider", min: 240, max: 680, step: 4, unit: "px" },
      default: "420px",
      scope: "shared",
      affects: ["cards", "media"],
    },
  ],
};

export const FORM_CATALOG: TokenGroupCatalog = {
  group: "Form",
  label: "Form fields",
  description: "Field backgrounds, hover/strong states, and focus ring.",
  tokens: [
    {
      token: "--primitive-field-bg",
      label: "Field background",
      description: "Resting input / field fill.",
      group: "Form",
      control: { kind: "color", supportsAlpha: true },
      default: "rgba(255, 255, 255, 0.055)",
      lightDefault: "rgba(255, 255, 255, 0.78)",
      scope: "themed",
      affects: ["fields"],
    },
    {
      token: "--primitive-size-row-sm",
      label: "Row sm",
      description: "Compact list, table, and settings row height.",
      group: "Form",
      control: { kind: "slider", min: 28, max: 56, step: 1, unit: "px" },
      default: "36px",
      scope: "shared",
      affects: ["fields", "tables"],
    },
    {
      token: "--primitive-size-row-md",
      label: "Row md",
      description: "Default list, table, and settings row height.",
      group: "Form",
      control: { kind: "slider", min: 32, max: 68, step: 1, unit: "px" },
      default: "44px",
      scope: "shared",
      affects: ["fields", "tables"],
    },
    {
      token: "--primitive-size-row-lg",
      label: "Row lg",
      description: "Large list, table, and settings row height.",
      group: "Form",
      control: { kind: "slider", min: 40, max: 80, step: 1, unit: "px" },
      default: "56px",
      scope: "shared",
      affects: ["fields", "tables"],
    },
    {
      token: "--primitive-size-field-sm",
      label: "Field sm",
      description: "Compact field height.",
      group: "Form",
      control: { kind: "slider", min: 28, max: 56, step: 1, unit: "px" },
      default: "36px",
      scope: "shared",
      affects: ["fields"],
    },
    {
      token: "--primitive-size-field-lg",
      label: "Field lg",
      description: "Large field height.",
      group: "Form",
      control: { kind: "slider", min: 40, max: 76, step: 1, unit: "px" },
      default: "52px",
      scope: "shared",
      affects: ["fields"],
    },
    {
      token: "--primitive-size-field-md",
      label: "Field md",
      description: "Default field height.",
      group: "Form",
      control: { kind: "slider", min: 36, max: 64, step: 1, unit: "px" },
      default: "44px",
      scope: "shared",
      affects: ["fields"],
    },
    {
      token: "--primitive-field-hover",
      label: "Field hover",
      description: "Field fill on hover.",
      group: "Form",
      control: { kind: "color", supportsAlpha: true },
      default: "rgba(255, 255, 255, 0.1)",
      lightDefault: "rgba(255, 255, 255, 0.94)",
      scope: "themed",
      affects: ["fields"],
    },
    {
      token: "--primitive-field-strong",
      label: "Field strong",
      description: "Field fill when focused / filled.",
      group: "Form",
      control: { kind: "color", supportsAlpha: true },
      default: "rgba(255, 255, 255, 0.14)",
      lightDefault: "rgba(255, 255, 255, 0.98)",
      scope: "themed",
      affects: ["fields"],
    },
    {
      token: "--primitive-focus-ring",
      label: "Focus ring",
      description: "Focus outline color (also caret color).",
      group: "Form",
      control: { kind: "color" },
      default: "#40bcff",
      lightDefault: "#087f83",
      scope: "themed",
      affects: ["focus", "fields"],
    },
    {
      token: "--primitive-focus-shadow",
      label: "Focus shadow",
      description: "Soft focus glow ring around focused elements.",
      group: "Form",
      control: {
        kind: "select",
        options: [
          { label: "Ring (dark)", value: "0 0 0 3px rgba(64, 188, 255, 0.24)" },
          { label: "Ring (light)", value: "0 0 0 3px rgba(8, 127, 131, 0.22)" },
          { label: "None", value: "none" },
        ],
      },
      default: "0 0 0 3px rgba(64, 188, 255, 0.24)",
      lightDefault: "0 0 0 3px rgba(8, 127, 131, 0.22)",
      scope: "themed",
      affects: ["focus", "fields"],
    },
  ],
};

export const NAV_CATALOG: TokenGroupCatalog = {
  group: "Nav",
  label: "Navigation",
  description: "Nav item surfaces, hover/active states, and borders.",
  tokens: [
    {
      token: "--primitive-nav-border",
      label: "Nav border",
      description: "Nav item edge color.",
      group: "Nav",
      control: { kind: "color", supportsAlpha: true },
      default: "rgba(255, 255, 255, 0.02)",
      lightDefault: "rgba(35, 45, 51, 0.1)",
      scope: "themed",
      affects: ["nav"],
    },
    {
      token: "--primitive-nav-surface",
      label: "Nav surface",
      description: "Resting nav item fill.",
      group: "Nav",
      control: { kind: "color", supportsAlpha: true },
      default:
        "linear-gradient(180deg, rgba(255, 255, 255, 0.04), rgba(255, 255, 255, 0.012)), rgba(255, 255, 255, 0.012)",
      scope: "themed",
      affects: ["nav"],
    },
    {
      token: "--primitive-nav-hover-surface",
      label: "Nav hover surface",
      description: "Nav item fill on hover.",
      group: "Nav",
      control: { kind: "color", supportsAlpha: true },
      default:
        "linear-gradient(180deg, rgba(255, 255, 255, 0.075), rgba(255, 255, 255, 0.02)), rgba(255, 255, 255, 0.04)",
      scope: "themed",
      affects: ["nav"],
    },
    {
      token: "--primitive-nav-active-surface",
      label: "Nav active surface",
      description: "Active / selected nav item fill (brand-red tinted).",
      group: "Nav",
      control: { kind: "color", supportsAlpha: true },
      default:
        "linear-gradient(135deg, rgba(230, 32, 40, 0.18), transparent 70%), linear-gradient(180deg, rgba(255, 255, 255, 0.06), rgba(255, 255, 255, 0.018)), rgba(255, 255, 255, 0.045)",
      scope: "themed",
      affects: ["nav"],
    },
  ],
};
