/**
 * Spacing + Radius token controls. Both scales are theme-agnostic (shared)
 * px-exact sliders.
 */
import type { TokenGroupCatalog } from "../types";

export const SPACING_CATALOG: TokenGroupCatalog = {
  group: "Spacing",
  label: "Spacing",
  description: "The px-exact spacing scale used for padding, margin, and gap rhythm.",
  tokens: [
    {
      token: "--primitive-space-0",
      label: "Space 0",
      description: "Zero spacing.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 0, step: 1, unit: "px" },
      default: "0",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-px",
      label: "Space px",
      description: "1px micro-gap (hairline rhythm).",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 4, step: 1, unit: "px" },
      default: "1px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-0-5",
      label: "Space 0.5",
      description: "2px micro-step.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 8, step: 1, unit: "px" },
      default: "2px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-1",
      label: "Space 1",
      description: "4px (base unit).",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 16, step: 1, unit: "px" },
      default: "4px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-1-5",
      label: "Space 1.5",
      description: "6px.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 16, step: 1, unit: "px" },
      default: "6px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-2",
      label: "Space 2",
      description: "8px.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 24, step: 1, unit: "px" },
      default: "8px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-2-5",
      label: "Space 2.5",
      description: "10px.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 24, step: 1, unit: "px" },
      default: "10px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-3",
      label: "Space 3",
      description: "12px.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 32, step: 1, unit: "px" },
      default: "12px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-4",
      label: "Space 4",
      description: "16px.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 48, step: 1, unit: "px" },
      default: "16px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-5",
      label: "Space 5",
      description: "20px.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 48, step: 1, unit: "px" },
      default: "20px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-6",
      label: "Space 6",
      description: "24px.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 64, step: 1, unit: "px" },
      default: "24px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-7",
      label: "Space 7",
      description: "28px.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 64, step: 1, unit: "px" },
      default: "28px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-8",
      label: "Space 8",
      description: "32px.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 96, step: 1, unit: "px" },
      default: "32px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-9",
      label: "Space 9",
      description: "40px.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 96, step: 1, unit: "px" },
      default: "40px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-10",
      label: "Space 10",
      description: "48px.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 128, step: 1, unit: "px" },
      default: "48px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-11",
      label: "Space 11",
      description: "56px.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 128, step: 1, unit: "px" },
      default: "56px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-12",
      label: "Space 12",
      description: "64px.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 192, step: 1, unit: "px" },
      default: "64px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-14",
      label: "Space 14",
      description: "80px.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 192, step: 1, unit: "px" },
      default: "80px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-16",
      label: "Space 16",
      description: "96px.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 256, step: 1, unit: "px" },
      default: "96px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-20",
      label: "Space 20",
      description: "128px.",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 320, step: 1, unit: "px" },
      default: "128px",
      scope: "shared",
      affects: ["all"],
    },
    {
      token: "--primitive-space-24",
      label: "Space 24",
      description: "160px (largest section rhythm).",
      group: "Spacing",
      control: { kind: "slider", min: 0, max: 320, step: 1, unit: "px" },
      default: "160px",
      scope: "shared",
      affects: ["all"],
    },
  ],
};

export const RADIUS_CATALOG: TokenGroupCatalog = {
  group: "Radius",
  label: "Radius",
  description: "Corner-radius scale from sharp to pill and round.",
  tokens: [
    {
      token: "--primitive-radius-none",
      label: "Radius none",
      description: "Sharp 0 corner.",
      group: "Radius",
      control: { kind: "slider", min: 0, max: 0, step: 1, unit: "px" },
      default: "0",
      scope: "shared",
      affects: ["panels", "cards", "buttons", "fields"],
    },
    {
      token: "--primitive-radius-xs",
      label: "Radius xs",
      description: "2px corner.",
      group: "Radius",
      control: { kind: "slider", min: 0, max: 8, step: 1, unit: "px" },
      default: "2px",
      scope: "shared",
      affects: ["panels", "cards", "buttons", "fields"],
    },
    {
      token: "--primitive-radius-sm",
      label: "Radius sm",
      description: "4px corner (button default).",
      group: "Radius",
      control: { kind: "slider", min: 0, max: 16, step: 1, unit: "px" },
      default: "4px",
      scope: "shared",
      affects: ["buttons", "fields", "cards"],
    },
    {
      token: "--primitive-radius-md",
      label: "Radius md",
      description: "8px corner.",
      group: "Radius",
      control: { kind: "slider", min: 0, max: 24, step: 1, unit: "px" },
      default: "8px",
      scope: "shared",
      affects: ["panels", "cards", "fields"],
    },
    {
      token: "--primitive-radius-lg",
      label: "Radius lg",
      description: "12px corner.",
      group: "Radius",
      control: { kind: "slider", min: 0, max: 32, step: 1, unit: "px" },
      default: "12px",
      scope: "shared",
      affects: ["panels", "cards"],
    },
    {
      token: "--primitive-radius-xl",
      label: "Radius xl",
      description: "16px corner.",
      group: "Radius",
      control: { kind: "slider", min: 0, max: 48, step: 1, unit: "px" },
      default: "16px",
      scope: "shared",
      affects: ["panels", "cards"],
    },
    {
      token: "--primitive-radius-2xl",
      label: "Radius 2xl",
      description: "24px corner (large panels).",
      group: "Radius",
      control: { kind: "slider", min: 0, max: 64, step: 1, unit: "px" },
      default: "24px",
      scope: "shared",
      affects: ["panels", "cards"],
    },
    {
      token: "--primitive-radius-pill",
      label: "Radius pill",
      description: "Fully rounded pill (999px).",
      group: "Radius",
      control: { kind: "slider", min: 0, max: 999, step: 1, unit: "px" },
      default: "999px",
      scope: "shared",
      affects: ["buttons", "controls"],
    },
    {
      token: "--primitive-radius-round",
      label: "Radius round",
      description: "Perfect circle (50%).",
      group: "Radius",
      control: { kind: "slider", min: 0, max: 50, step: 1, unit: "%" },
      default: "50%",
      scope: "shared",
      affects: ["controls", "icons"],
    },
  ],
};
