/**
 * Typography token controls. Theme-agnostic (shared) — sizes/weights/tracking
 * do not change between light and dark.
 *
 * Font families are select controls (named stacks). The fluid heading scale
 * uses clamp() and is exposed as read-only-ish select presets; the fixed UI
 * sizes are rem sliders.
 */
import type { SelectOption, TokenGroupCatalog } from "../types";

const FONT_FAMILY_OPTIONS: readonly SelectOption[] = [
  { label: "Display (Oswald / Anton)", value: "var(--primitive-font-display)" },
  { label: "Display alt (Anton)", value: "var(--primitive-font-display-alt)" },
  { label: "Body (Geist / Inter)", value: "var(--primitive-font-body)" },
  { label: "Mono (JetBrains Mono)", value: "var(--primitive-font-mono)" },
  { label: "Mono techno", value: "var(--primitive-font-mono-techno)" },
];

const WEIGHT_OPTIONS: readonly SelectOption[] = [
  { label: "Regular (400)", value: "400" },
  { label: "Medium (500)", value: "500" },
  { label: "Semibold (600)", value: "600" },
  { label: "Bold (700)", value: "700" },
  { label: "Black (900)", value: "900" },
];

export const TYPOGRAPHY_CATALOG: TokenGroupCatalog = {
  group: "Typography",
  label: "Typography",
  description:
    "Font families, the fluid + fixed type scale, weights, line-heights, and tracking.",
  tokens: [
    // ---- Font families ----
    {
      token: "--primitive-font-display",
      label: "Display font",
      description: "Heading / display typeface stack.",
      group: "Typography",
      control: { kind: "select", options: FONT_FAMILY_OPTIONS },
      default: "var(--ff-oswald, var(--ff-anton, var(--font-display, Anton, Impact, sans-serif)))",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-font-body",
      label: "Body font",
      description: "Default body / UI typeface stack.",
      group: "Typography",
      control: { kind: "select", options: FONT_FAMILY_OPTIONS },
      default: "var(--ff-geist, var(--font-body, Inter, Arial, sans-serif))",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-font-mono",
      label: "Mono font",
      description: "Monospace typeface for code and technical labels.",
      group: "Typography",
      control: { kind: "select", options: FONT_FAMILY_OPTIONS },
      default: 'var(--ff-primitive-mono, var(--ff-geist-mono, var(--font-mono, "JetBrains Mono", monospace)))',
      scope: "shared",
      affects: ["typography", "code"],
    },
    // ---- Fluid headings (rem sliders, clamp-driven max) ----
    {
      token: "--primitive-display",
      label: "Display size",
      description: "Hero display size (fluid clamp; slider sets the rem cap).",
      group: "Typography",
      control: { kind: "slider", min: 3, max: 9, step: 0.25, unit: "rem" },
      default: "clamp(3rem, 1rem + 7vw, 7.5rem)",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-h1",
      label: "Heading 1",
      description: "H1 size (fluid clamp).",
      group: "Typography",
      control: { kind: "slider", min: 2, max: 5, step: 0.125, unit: "rem" },
      default: "clamp(2.25rem, 1.2rem + 4vw, 4rem)",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-h2",
      label: "Heading 2",
      description: "H2 size (fluid clamp).",
      group: "Typography",
      control: { kind: "slider", min: 1.5, max: 3.5, step: 0.125, unit: "rem" },
      default: "clamp(1.6rem, 1.1rem + 2vw, 2.5rem)",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-h3",
      label: "Heading 3",
      description: "H3 size (fluid clamp).",
      group: "Typography",
      control: { kind: "slider", min: 1.25, max: 2.5, step: 0.0625, unit: "rem" },
      default: "clamp(1.3rem, 1rem + 1.2vw, 1.75rem)",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-h4",
      label: "Heading 4",
      description: "H4 fixed size.",
      group: "Typography",
      control: { kind: "slider", min: 1, max: 1.75, step: 0.0625, unit: "rem" },
      default: "1.25rem",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-h5",
      label: "Heading 5",
      description: "H5 fixed size.",
      group: "Typography",
      control: { kind: "slider", min: 0.875, max: 1.5, step: 0.0625, unit: "rem" },
      default: "1.0625rem",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-h6",
      label: "Heading 6",
      description: "H6 fixed size.",
      group: "Typography",
      control: { kind: "slider", min: 0.75, max: 1.25, step: 0.0625, unit: "rem" },
      default: "0.9375rem",
      scope: "shared",
      affects: ["typography"],
    },
    // ---- Fixed UI sizes ----
    {
      token: "--primitive-text-2xs",
      label: "Text 2xs",
      description: "Smallest UI text (10px).",
      group: "Typography",
      control: { kind: "slider", min: 0.5, max: 0.875, step: 0.0625, unit: "rem" },
      default: "0.625rem",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-text-xs",
      label: "Text xs",
      description: "Extra-small UI text (12px).",
      group: "Typography",
      control: { kind: "slider", min: 0.625, max: 1, step: 0.0625, unit: "rem" },
      default: "0.75rem",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-text-sm",
      label: "Text sm",
      description: "Small UI text (13px).",
      group: "Typography",
      control: { kind: "slider", min: 0.6875, max: 1.0625, step: 0.0625, unit: "rem" },
      default: "0.8125rem",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-text-base",
      label: "Text base",
      description: "Base UI text (15px).",
      group: "Typography",
      control: { kind: "slider", min: 0.75, max: 1.25, step: 0.0625, unit: "rem" },
      default: "0.9375rem",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-text-md",
      label: "Text md",
      description: "Medium body text (16px).",
      group: "Typography",
      control: { kind: "slider", min: 0.875, max: 1.375, step: 0.0625, unit: "rem" },
      default: "1rem",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-text-lg",
      label: "Text lg",
      description: "Large body text (18px).",
      group: "Typography",
      control: { kind: "slider", min: 1, max: 1.5, step: 0.0625, unit: "rem" },
      default: "1.125rem",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-text-xl",
      label: "Text xl",
      description: "Extra-large text (22px).",
      group: "Typography",
      control: { kind: "slider", min: 1.125, max: 1.875, step: 0.0625, unit: "rem" },
      default: "1.375rem",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-text-2xl",
      label: "Text 2xl",
      description: "Section-lead text (28px).",
      group: "Typography",
      control: { kind: "slider", min: 1.5, max: 2.5, step: 0.0625, unit: "rem" },
      default: "1.75rem",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-text-3xl",
      label: "Text 3xl",
      description: "Largest fixed text (36px).",
      group: "Typography",
      control: { kind: "slider", min: 1.875, max: 3, step: 0.0625, unit: "rem" },
      default: "2.25rem",
      scope: "shared",
      affects: ["typography"],
    },
    // ---- Weights ----
    {
      token: "--primitive-weight-regular",
      label: "Weight regular",
      description: "Regular font weight.",
      group: "Typography",
      control: { kind: "select", options: WEIGHT_OPTIONS },
      default: "400",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-weight-medium",
      label: "Weight medium",
      description: "Medium font weight.",
      group: "Typography",
      control: { kind: "select", options: WEIGHT_OPTIONS },
      default: "500",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-weight-semibold",
      label: "Weight semibold",
      description: "Semibold font weight.",
      group: "Typography",
      control: { kind: "select", options: WEIGHT_OPTIONS },
      default: "600",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-weight-bold",
      label: "Weight bold",
      description: "Bold font weight.",
      group: "Typography",
      control: { kind: "select", options: WEIGHT_OPTIONS },
      default: "700",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-weight-black",
      label: "Weight black",
      description: "Black / heaviest font weight.",
      group: "Typography",
      control: { kind: "select", options: WEIGHT_OPTIONS },
      default: "900",
      scope: "shared",
      affects: ["typography"],
    },
    // ---- Line heights (unitless sliders) ----
    {
      token: "--primitive-leading-none",
      label: "Leading none",
      description: "Line-height 1 (tightest).",
      group: "Typography",
      control: { kind: "slider", min: 0.85, max: 1.2, step: 0.05, unit: "" },
      default: "1",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-leading-tight",
      label: "Leading tight",
      description: "Compressed display line-height.",
      group: "Typography",
      control: { kind: "slider", min: 0.85, max: 1.2, step: 0.05, unit: "" },
      default: "0.95",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-leading-snug",
      label: "Leading snug",
      description: "Snug heading line-height.",
      group: "Typography",
      control: { kind: "slider", min: 1, max: 1.4, step: 0.05, unit: "" },
      default: "1.15",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-leading-normal",
      label: "Leading normal",
      description: "Default body line-height.",
      group: "Typography",
      control: { kind: "slider", min: 1.2, max: 1.8, step: 0.05, unit: "" },
      default: "1.5",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-leading-relaxed",
      label: "Leading relaxed",
      description: "Loose line-height for long-form reading.",
      group: "Typography",
      control: { kind: "slider", min: 1.4, max: 2, step: 0.05, unit: "" },
      default: "1.7",
      scope: "shared",
      affects: ["typography"],
    },
    // ---- Letter spacing (em sliders) ----
    {
      token: "--primitive-tracking-tight",
      label: "Tracking tight",
      description: "Negative tracking for large display.",
      group: "Typography",
      control: { kind: "slider", min: -0.05, max: 0, step: 0.005, unit: "em" },
      default: "-0.01em",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-tracking-normal",
      label: "Tracking normal",
      description: "Default (zero) tracking.",
      group: "Typography",
      control: { kind: "slider", min: 0, max: 0.05, step: 0.005, unit: "em" },
      default: "0",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-tracking-wide",
      label: "Tracking wide",
      description: "Wide tracking for labels.",
      group: "Typography",
      control: { kind: "slider", min: 0.04, max: 0.16, step: 0.01, unit: "em" },
      default: "0.08em",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-tracking-wider",
      label: "Tracking wider",
      description: "Wider tracking for eyebrows.",
      group: "Typography",
      control: { kind: "slider", min: 0.1, max: 0.24, step: 0.01, unit: "em" },
      default: "0.16em",
      scope: "shared",
      affects: ["typography"],
    },
    {
      token: "--primitive-tracking-widest",
      label: "Tracking widest",
      description: "Widest tracking for caps mono labels.",
      group: "Typography",
      control: { kind: "slider", min: 0.16, max: 0.32, step: 0.01, unit: "em" },
      default: "0.22em",
      scope: "shared",
      affects: ["typography"],
    },
  ],
};
